import type { Metadata } from "next";
import InformationPage, { type InformationSection } from "@/components/guest/InformationPage";

export const metadata: Metadata = { title: "Chính sách bảo mật" };

const sections: InformationSection[] = [
  { title: { vi: "Dữ liệu được thu thập", en: "Data we collect" }, body: { vi: "Hệ thống xử lý họ tên, email, số điện thoại, địa chỉ, thông tin kỳ lưu trú, hạng và số lượng phòng, yêu cầu đặc biệt, lịch sử trạng thái đơn và dữ liệu đối soát thanh toán/hoàn tiền.", en: "The system processes names, email, phone, address, stay details, room types and quantities, special requests, booking status history, and payment/refund reconciliation data." } },
  { title: { vi: "Dữ liệu thanh toán", en: "Payment data" }, body: { vi: "Website hiển thị tài khoản nhận, số tiền và nội dung chuyển khoản. Hệ thống không yêu cầu OTP, PIN hoặc mật khẩu ngân hàng. Xác nhận từ ngân hàng được dùng để đối soát giao dịch và duy trì ledger.", en: "The website displays the recipient account, amount, and transfer reference. It never asks for an OTP, PIN, or bank password. Bank confirmations reconcile transactions and maintain the ledger." } },
  { title: { vi: "Mục đích sử dụng", en: "How data is used" }, body: { vi: "Dữ liệu được dùng để kiểm tra phòng trống, tạo và quản lý đơn, hỗ trợ check-in/check-out, xử lý hủy và hoàn tiền, gửi thông báo và phục vụ audit vận hành.", en: "Data supports availability checks, booking management, check-in/out, cancellations and refunds, notifications, and operational audits." } },
  { title: { vi: "Phiên khách và quyền truy cập", en: "Guest sessions and access" }, body: { vi: "Khách không đăng nhập nhận token tra cứu riêng. Quyền truy cập được giới hạn theo vai trò khách, nhân viên và quản trị viên; không chia sẻ liên kết hoặc token tra cứu cho người khác.", en: "Guests without accounts receive a private lookup token. Access is role-limited for guests, staff, and administrators; do not share lookup links or tokens." } },
  { title: { vi: "Lưu trữ dữ liệu", en: "Data retention" }, body: { vi: "Dữ liệu được lưu trong thời gian cần thiết để cung cấp dịch vụ, bảo vệ tài khoản, đối soát giao dịch và giải quyết tranh chấp. Hồ sơ đặt phòng, tài chính và audit có thể được giữ lâu hơn khi pháp luật hoặc nghĩa vụ kế toán yêu cầu; dữ liệu không còn cần thiết sẽ được xóa hoặc ẩn danh an toàn.", en: "Data is retained only as long as needed to provide the service, protect accounts, reconcile transactions, and resolve disputes. Booking, financial, and audit records may be kept longer when required by law or accounting obligations; data no longer needed is securely deleted or anonymized." } },
  { title: { vi: "Quyền truy cập, sửa và xóa", en: "Access, correction, and deletion" }, body: { vi: "Bạn có thể gửi yêu cầu truy cập, chỉnh sửa hoặc xóa dữ liệu qua Trung tâm hỗ trợ. Khách sạn sẽ xác minh danh tính trước khi xử lý. Việc xóa tài khoản không làm mất các chứng từ tài chính hoặc audit bắt buộc phải lưu, nhưng các dữ liệu không còn căn cứ lưu trữ sẽ được xóa hoặc ẩn danh.", en: "You can request access, correction, or deletion through the Support Center. The hotel verifies identity before processing. Account deletion does not remove financial or audit records that must legally be retained, while data without a continuing retention basis is deleted or anonymized." } },
];

export default function PrivacyPage() {
  return <InformationPage eyebrow={{ vi: "Quyền riêng tư", en: "Privacy" }} title={{ vi: "Chính sách bảo mật", en: "Privacy policy" }} intro={{ vi: "Dữ liệu nào được xử lý, vì sao cần dữ liệu đó và cách giữ an toàn thông tin đặt phòng.", en: "What data is processed, why it is needed, and how booking information is protected." }} sections={sections} notice={{ vi: "Luxury Hotel không bao giờ yêu cầu mật khẩu, OTP, PIN hoặc mật khẩu ngân hàng trong biểu mẫu hỗ trợ.", en: "Luxury Hotel never asks for passwords, OTPs, PINs, or bank passwords in support forms." }} primaryAction={{ href: "/data-deletion", label: { vi: "Yêu cầu xóa dữ liệu", en: "Request data deletion" } }} secondaryAction={{ href: "/terms", label: { vi: "Điều khoản sử dụng", en: "Terms of use" } }} />;
}
