-- Paid add-on services are separate from free hotel facilities. Catalog rows
-- are soft-deactivated; reservation lines retain immutable pricing snapshots.

CREATE TABLE service_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    code varchar(64) NOT NULL,
    name varchar(255) NOT NULL,
    name_en varchar(255),
    description text,
    description_en text,
    image_url varchar(500),
    category varchar(32) NOT NULL,
    price decimal(12,2) NOT NULL,
    pricing_unit varchar(32) NOT NULL,
    booking_enabled boolean NOT NULL DEFAULT true,
    in_stay_enabled boolean NOT NULL DEFAULT true,
    is_active boolean NOT NULL DEFAULT true,
    sort_order int NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT uk_service_catalog_code UNIQUE (code),
    CONSTRAINT chk_service_catalog_category CHECK (
        category IN ('FOOD_BEVERAGE','AMENITY','EQUIPMENT','DECORATION','OTHER')),
    CONSTRAINT chk_service_catalog_pricing_unit CHECK (
        pricing_unit IN ('PER_GUEST','PER_NIGHT','PER_ITEM','PER_ORDER','PER_USE')),
    CONSTRAINT chk_service_catalog_price CHECK (price >= 0),
    CONSTRAINT chk_service_catalog_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_service_catalog_active_sort
    ON service_catalog (is_active, sort_order, id);

CREATE TABLE reservation_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    reservation_id bigint NOT NULL,
    service_id bigint NOT NULL,
    origin varchar(24) NOT NULL,
    service_code_snapshot varchar(64) NOT NULL,
    service_name_snapshot varchar(255) NOT NULL,
    service_name_en_snapshot varchar(255),
    service_image_url_snapshot varchar(500),
    unit_price_snapshot decimal(12,2) NOT NULL,
    pricing_unit_snapshot varchar(32) NOT NULL,
    quantity int NOT NULL,
    pricing_multiplier int NOT NULL DEFAULT 1,
    billable_quantity int NOT NULL,
    total_price decimal(12,2) NOT NULL,
    status varchar(24) NOT NULL,
    notes text,
    cancellation_reason varchar(500),
    requested_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    confirmed_at_utc TIMESTAMP(6) WITH TIME ZONE,
    fulfilled_at_utc TIMESTAMP(6) WITH TIME ZONE,
    cancelled_at_utc TIMESTAMP(6) WITH TIME ZONE,
    requested_by_user_id bigint,
    last_updated_by_user_id bigint,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT fk_reservation_services_reservation
        FOREIGN KEY (reservation_id) REFERENCES reservations (id),
    CONSTRAINT fk_reservation_services_catalog
        FOREIGN KEY (service_id) REFERENCES service_catalog (id),
    CONSTRAINT fk_reservation_services_requested_by
        FOREIGN KEY (requested_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_reservation_services_updated_by
        FOREIGN KEY (last_updated_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT chk_reservation_services_origin CHECK (
        origin IN ('BOOKING_TIME','IN_STAY')),
    CONSTRAINT chk_reservation_services_pricing_unit CHECK (
        pricing_unit_snapshot IN ('PER_GUEST','PER_NIGHT','PER_ITEM','PER_ORDER','PER_USE')),
    CONSTRAINT chk_reservation_services_status CHECK (
        status IN ('REQUESTED','CONFIRMED','FULFILLED','CANCELLED')),
    CONSTRAINT chk_reservation_services_quantity CHECK (quantity > 0),
    CONSTRAINT chk_reservation_services_multiplier CHECK (pricing_multiplier > 0),
    CONSTRAINT chk_reservation_services_billable_quantity CHECK (billable_quantity > 0),
    CONSTRAINT chk_reservation_services_unit_price CHECK (unit_price_snapshot >= 0),
    CONSTRAINT chk_reservation_services_total CHECK (
        total_price = unit_price_snapshot * billable_quantity)
);

CREATE INDEX idx_reservation_services_reservation_status
    ON reservation_services (reservation_id, status, id);
CREATE INDEX idx_reservation_services_service
    ON reservation_services (service_id, id);

ALTER TABLE reservation_invoices
    ADD COLUMN add_on_service_amount decimal(19,2);

UPDATE reservation_invoices
SET add_on_service_amount = 0
WHERE add_on_service_amount IS NULL;

ALTER TABLE reservation_invoices
    ALTER COLUMN add_on_service_amount SET DEFAULT 0,
    ALTER COLUMN add_on_service_amount SET NOT NULL;
