-- Pricing engine V2 foundation only.
-- The runtime feature flag remains OFF, so existing reservations continue to
-- use LEGACY_V1 and no historical monetary value is recalculated.

ALTER TABLE room_types
    ADD COLUMN code varchar(40);

DO $$
BEGIN
    IF EXISTS (
        WITH canonical AS (
            SELECT CASE
                WHEN lower(trim(coalesce(type_name_en, ''))) = 'standard'
                  OR lower(trim(coalesce(type_name, ''))) = 'phòng tiêu chuẩn'
                    THEN 'STANDARD'
                WHEN lower(trim(coalesce(type_name_en, ''))) = 'deluxe'
                  OR lower(trim(coalesce(type_name, ''))) = 'phòng deluxe'
                    THEN 'DELUXE'
                WHEN lower(trim(coalesce(type_name_en, ''))) = 'executive room'
                  OR lower(trim(coalesce(type_name, ''))) = 'phòng executive'
                    THEN 'EXECUTIVE'
                WHEN lower(trim(coalesce(type_name_en, ''))) = 'suite'
                  OR lower(trim(coalesce(type_name, ''))) = 'phòng suite'
                    THEN 'SUITE'
                WHEN lower(trim(coalesce(type_name_en, ''))) = 'family room'
                  OR lower(trim(coalesce(type_name, ''))) = 'phòng gia đình'
                    THEN 'FAMILY'
                WHEN lower(trim(coalesce(type_name_en, ''))) = 'presidential suite'
                  OR lower(trim(coalesce(type_name, ''))) = 'phòng tổng thống'
                    THEN 'PRESIDENTIAL'
                ELSE NULL
            END AS code
            FROM room_types
        )
        SELECT 1
        FROM canonical
        WHERE code IS NOT NULL
        GROUP BY code
        HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION
            'Pricing V2 preflight failed: duplicate canonical room type';
    END IF;
END;
$$;

UPDATE room_types
SET code = CASE
    WHEN lower(trim(coalesce(type_name_en, ''))) = 'standard'
      OR lower(trim(coalesce(type_name, ''))) = 'phòng tiêu chuẩn'
        THEN 'STANDARD'
    WHEN lower(trim(coalesce(type_name_en, ''))) = 'deluxe'
      OR lower(trim(coalesce(type_name, ''))) = 'phòng deluxe'
        THEN 'DELUXE'
    WHEN lower(trim(coalesce(type_name_en, ''))) = 'executive room'
      OR lower(trim(coalesce(type_name, ''))) = 'phòng executive'
        THEN 'EXECUTIVE'
    WHEN lower(trim(coalesce(type_name_en, ''))) = 'suite'
      OR lower(trim(coalesce(type_name, ''))) = 'phòng suite'
        THEN 'SUITE'
    WHEN lower(trim(coalesce(type_name_en, ''))) = 'family room'
      OR lower(trim(coalesce(type_name, ''))) = 'phòng gia đình'
        THEN 'FAMILY'
    WHEN lower(trim(coalesce(type_name_en, ''))) = 'presidential suite'
      OR lower(trim(coalesce(type_name, ''))) = 'phòng tổng thống'
        THEN 'PRESIDENTIAL'
    ELSE 'ROOM_TYPE_' || id
END;

ALTER TABLE room_types
    ALTER COLUMN code SET NOT NULL;

ALTER TABLE room_types
    ADD CONSTRAINT uk_room_types_code UNIQUE (code);

ALTER TABLE reservations
    ADD COLUMN pricing_version varchar(32) NOT NULL DEFAULT 'LEGACY_V1',
    ADD COLUMN display_package_summary varchar(24),
    ADD COLUMN inventory_protected_until timestamp(6) without time zone;

ALTER TABLE reservations
    ADD CONSTRAINT chk_reservations_pricing_version
        CHECK (pricing_version IN ('LEGACY_V1', 'MOTEL_PACKAGE_V2')),
    ADD CONSTRAINT chk_reservations_display_package
        CHECK (display_package_summary IS NULL
            OR display_package_summary IN ('HOURLY', 'OVERNIGHT', 'DAILY'));

ALTER TABLE reservation_room_types
    ADD COLUMN line_guest_count integer,
    ADD COLUMN minimum_committed_room_charge decimal(14,2),
    ADD COLUMN max_package_reached varchar(24);

ALTER TABLE reservation_room_types
    ADD CONSTRAINT chk_rrt_line_guest_count
        CHECK (line_guest_count IS NULL OR line_guest_count >= 0),
    ADD CONSTRAINT chk_rrt_minimum_committed_charge
        CHECK (minimum_committed_room_charge IS NULL
            OR minimum_committed_room_charge >= 0),
    ADD CONSTRAINT chk_rrt_max_package_reached
        CHECK (max_package_reached IS NULL
            OR max_package_reached IN ('HOURLY', 'OVERNIGHT', 'DAILY'));

CREATE TABLE stay_policy_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_code varchar(64) NOT NULL,
    policy_version integer NOT NULL,
    grace_minutes integer NOT NULL,
    overnight_start_time time NOT NULL,
    overnight_early_morning_end time NOT NULL,
    overnight_hard_checkout_time time NOT NULL,
    overnight_maximum_minutes integer NOT NULL,
    daily_threshold_minutes integer NOT NULL,
    daily_duration_minutes integer NOT NULL,
    turnover_buffer_minutes integer NOT NULL,
    inventory_protection_mode varchar(32) NOT NULL
        DEFAULT 'PACKAGE_ENTITLEMENT',
    effective_from_utc timestamp with time zone NOT NULL,
    effective_to_utc timestamp with time zone,
    active boolean NOT NULL DEFAULT true,
    created_by_user_id bigint,
    created_at_utc timestamp with time zone NOT NULL,
    CONSTRAINT uk_stay_policy_code_version
        UNIQUE (policy_code, policy_version),
    CONSTRAINT fk_stay_policy_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_stay_policy_grace
        CHECK (grace_minutes BETWEEN 0 AND 60),
    CONSTRAINT chk_stay_policy_overnight_max
        CHECK (overnight_maximum_minutes BETWEEN 1 AND 1440),
    CONSTRAINT chk_stay_policy_daily_threshold
        CHECK (daily_threshold_minutes BETWEEN 1 AND daily_duration_minutes),
    CONSTRAINT chk_stay_policy_daily_duration
        CHECK (daily_duration_minutes >= 60),
    CONSTRAINT chk_stay_policy_turnover
        CHECK (turnover_buffer_minutes BETWEEN 0 AND 1440),
    CONSTRAINT chk_stay_policy_inventory_protection
        CHECK (inventory_protection_mode IN (
            'PACKAGE_ENTITLEMENT', 'PLANNED_STAY')),
    CONSTRAINT chk_stay_policy_effective_range
        CHECK (effective_to_utc IS NULL
            OR effective_to_utc > effective_from_utc)
);

CREATE UNIQUE INDEX uk_stay_policy_open_version
    ON stay_policy_versions(policy_code)
    WHERE active = true AND effective_to_utc IS NULL;

CREATE INDEX idx_stay_policy_effective
    ON stay_policy_versions(policy_code, effective_from_utc, effective_to_utc);

CREATE TABLE room_rate_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_type_id bigint NOT NULL,
    stay_policy_version_id bigint NOT NULL,
    profile_version integer NOT NULL,
    included_guests integer NOT NULL,
    first_block_minutes integer NOT NULL,
    first_block_price decimal(14,2) NOT NULL,
    extra_unit_minutes integer NOT NULL,
    extra_unit_price decimal(14,2) NOT NULL,
    overnight_price decimal(14,2) NOT NULL,
    daily_price decimal(14,2) NOT NULL,
    extra_guest_price decimal(14,2) NOT NULL,
    extra_guest_billing_mode varchar(32) NOT NULL
        DEFAULT 'PER_PACKAGE_CYCLE',
    effective_from_utc timestamp with time zone NOT NULL,
    effective_to_utc timestamp with time zone,
    active boolean NOT NULL DEFAULT true,
    created_by_user_id bigint,
    created_at_utc timestamp with time zone NOT NULL,
    CONSTRAINT uk_room_rate_profile_version
        UNIQUE (room_type_id, profile_version),
    CONSTRAINT fk_room_rate_profile_room_type
        FOREIGN KEY (room_type_id) REFERENCES room_types(id),
    CONSTRAINT fk_room_rate_profile_policy
        FOREIGN KEY (stay_policy_version_id) REFERENCES stay_policy_versions(id),
    CONSTRAINT fk_room_rate_profile_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_room_rate_profile_guests
        CHECK (included_guests >= 1),
    CONSTRAINT chk_room_rate_profile_first_block
        CHECK (first_block_minutes >= 1 AND first_block_price >= 0),
    CONSTRAINT chk_room_rate_profile_extra_unit
        CHECK (extra_unit_minutes >= 1 AND extra_unit_price >= 0),
    CONSTRAINT chk_room_rate_profile_prices
        CHECK (overnight_price >= 0
            AND daily_price >= 0
            AND extra_guest_price >= 0),
    CONSTRAINT chk_room_rate_profile_guest_mode
        CHECK (extra_guest_billing_mode = 'PER_PACKAGE_CYCLE'),
    CONSTRAINT chk_room_rate_profile_effective_range
        CHECK (effective_to_utc IS NULL
            OR effective_to_utc > effective_from_utc)
);

CREATE UNIQUE INDEX uk_room_rate_profile_open_version
    ON room_rate_profiles(room_type_id)
    WHERE active = true AND effective_to_utc IS NULL;

CREATE INDEX idx_room_rate_profile_effective
    ON room_rate_profiles(room_type_id, effective_from_utc, effective_to_utc);

CREATE OR REPLACE FUNCTION validate_room_rate_profile_capacity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    room_capacity integer;
BEGIN
    SELECT max_guests
    INTO room_capacity
    FROM room_types
    WHERE id = NEW.room_type_id;

    IF room_capacity IS NOT NULL
       AND NEW.included_guests > room_capacity THEN
        RAISE EXCEPTION
            'room_rate_profiles.included_guests (%) exceeds room type capacity (%)',
            NEW.included_guests, room_capacity
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_room_rate_profiles_validate_capacity
BEFORE INSERT OR UPDATE OF room_type_id, included_guests
ON room_rate_profiles
FOR EACH ROW
EXECUTE FUNCTION validate_room_rate_profile_capacity();

CREATE OR REPLACE FUNCTION protect_stay_policy_version()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'stay_policy_versions is versioned and cannot be deleted'
            USING ERRCODE = '55000';
    END IF;

    IF OLD.policy_code IS DISTINCT FROM NEW.policy_code
       OR OLD.policy_version IS DISTINCT FROM NEW.policy_version
       OR OLD.grace_minutes IS DISTINCT FROM NEW.grace_minutes
       OR OLD.overnight_start_time IS DISTINCT FROM NEW.overnight_start_time
       OR OLD.overnight_early_morning_end
            IS DISTINCT FROM NEW.overnight_early_morning_end
       OR OLD.overnight_hard_checkout_time
            IS DISTINCT FROM NEW.overnight_hard_checkout_time
       OR OLD.overnight_maximum_minutes
            IS DISTINCT FROM NEW.overnight_maximum_minutes
       OR OLD.daily_threshold_minutes
            IS DISTINCT FROM NEW.daily_threshold_minutes
       OR OLD.daily_duration_minutes
            IS DISTINCT FROM NEW.daily_duration_minutes
       OR OLD.turnover_buffer_minutes
            IS DISTINCT FROM NEW.turnover_buffer_minutes
       OR OLD.inventory_protection_mode
            IS DISTINCT FROM NEW.inventory_protection_mode
       OR OLD.effective_from_utc IS DISTINCT FROM NEW.effective_from_utc
       OR OLD.created_by_user_id IS DISTINCT FROM NEW.created_by_user_id
       OR OLD.created_at_utc IS DISTINCT FROM NEW.created_at_utc THEN
        RAISE EXCEPTION
            'stay_policy_versions financial policy is immutable; create a new version'
            USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_stay_policy_versions_protect_version
BEFORE UPDATE OR DELETE ON stay_policy_versions
FOR EACH ROW
EXECUTE FUNCTION protect_stay_policy_version();

CREATE OR REPLACE FUNCTION protect_room_rate_profile_version()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'room_rate_profiles is versioned and cannot be deleted'
            USING ERRCODE = '55000';
    END IF;

    IF OLD.room_type_id IS DISTINCT FROM NEW.room_type_id
       OR OLD.stay_policy_version_id
            IS DISTINCT FROM NEW.stay_policy_version_id
       OR OLD.profile_version IS DISTINCT FROM NEW.profile_version
       OR OLD.included_guests IS DISTINCT FROM NEW.included_guests
       OR OLD.first_block_minutes IS DISTINCT FROM NEW.first_block_minutes
       OR OLD.first_block_price IS DISTINCT FROM NEW.first_block_price
       OR OLD.extra_unit_minutes IS DISTINCT FROM NEW.extra_unit_minutes
       OR OLD.extra_unit_price IS DISTINCT FROM NEW.extra_unit_price
       OR OLD.overnight_price IS DISTINCT FROM NEW.overnight_price
       OR OLD.daily_price IS DISTINCT FROM NEW.daily_price
       OR OLD.extra_guest_price IS DISTINCT FROM NEW.extra_guest_price
       OR OLD.extra_guest_billing_mode
            IS DISTINCT FROM NEW.extra_guest_billing_mode
       OR OLD.effective_from_utc IS DISTINCT FROM NEW.effective_from_utc
       OR OLD.created_by_user_id IS DISTINCT FROM NEW.created_by_user_id
       OR OLD.created_at_utc IS DISTINCT FROM NEW.created_at_utc THEN
        RAISE EXCEPTION
            'room_rate_profiles financial rates are immutable; create a new version'
            USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_room_rate_profiles_protect_version
BEFORE UPDATE OR DELETE ON room_rate_profiles
FOR EACH ROW
EXECUTE FUNCTION protect_room_rate_profile_version();

CREATE OR REPLACE FUNCTION protect_room_type_capacity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.max_guests < OLD.max_guests
       AND EXISTS (
           SELECT 1
           FROM room_rate_profiles
           WHERE room_type_id = OLD.id
             AND active = true
             AND included_guests > NEW.max_guests
       ) THEN
        RAISE EXCEPTION
            'room_types.max_guests cannot be lower than active included guests'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_room_types_protect_capacity
BEFORE UPDATE OF max_guests ON room_types
FOR EACH ROW
EXECUTE FUNCTION protect_room_type_capacity();

CREATE TABLE reservation_rate_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_room_type_id bigint NOT NULL,
    snapshot_sequence integer NOT NULL,
    snapshot_stage varchar(24) NOT NULL,
    stay_policy_version_id bigint NOT NULL,
    rate_profile_id bigint NOT NULL,
    pricing_algorithm_version varchar(32) NOT NULL,
    committed_check_in timestamp(6) without time zone NOT NULL,
    committed_check_out timestamp(6) without time zone NOT NULL,
    actual_check_in timestamp(6) without time zone,
    actual_check_out timestamp(6) without time zone,
    stay_classification varchar(24) NOT NULL,
    initial_package varchar(24) NOT NULL,
    applied_package varchar(24) NOT NULL,
    max_package_reached varchar(24) NOT NULL,
    transition_reason varchar(40) NOT NULL,
    included_guests integer NOT NULL,
    max_guests_snapshot integer NOT NULL,
    line_guest_count integer NOT NULL,
    room_quantity integer NOT NULL,
    extra_guest_count integer NOT NULL,
    first_block_minutes integer NOT NULL,
    first_block_price decimal(14,2) NOT NULL,
    extra_unit_minutes integer NOT NULL,
    extra_unit_price decimal(14,2) NOT NULL,
    grace_minutes integer NOT NULL,
    overnight_price decimal(14,2) NOT NULL,
    overnight_included_checkout timestamp(6) without time zone,
    daily_price decimal(14,2) NOT NULL,
    daily_duration_minutes integer NOT NULL,
    full_days integer NOT NULL,
    remainder_minutes integer NOT NULL,
    charged_extra_units integer NOT NULL,
    minimum_committed_room_charge decimal(14,2) NOT NULL,
    final_room_charge decimal(14,2) NOT NULL,
    extra_guest_charge decimal(14,2) NOT NULL,
    allocated_service_charge decimal(14,2) NOT NULL,
    adjustment_amount decimal(14,2) NOT NULL,
    breakdown_json jsonb NOT NULL,
    snapshot_hash char(64) NOT NULL,
    created_at_utc timestamp with time zone NOT NULL,
    CONSTRAINT uk_reservation_rate_snapshot_sequence
        UNIQUE (reservation_room_type_id, snapshot_sequence),
    CONSTRAINT fk_rate_snapshot_reservation_room_type
        FOREIGN KEY (reservation_room_type_id) REFERENCES reservation_room_types(id),
    CONSTRAINT fk_rate_snapshot_policy
        FOREIGN KEY (stay_policy_version_id) REFERENCES stay_policy_versions(id),
    CONSTRAINT fk_rate_snapshot_profile
        FOREIGN KEY (rate_profile_id) REFERENCES room_rate_profiles(id),
    CONSTRAINT chk_rate_snapshot_stage
        CHECK (snapshot_stage IN (
            'COMMITMENT', 'CHECK_IN', 'EXTENSION', 'CHECKOUT', 'ADJUSTMENT')),
    CONSTRAINT chk_rate_snapshot_algorithm
        CHECK (pricing_algorithm_version = 'MOTEL_PACKAGE_V2'),
    CONSTRAINT chk_rate_snapshot_classification
        CHECK (stay_classification IN ('DAY_STAY', 'NIGHT_STAY', 'MULTI_DAY')),
    CONSTRAINT chk_rate_snapshot_packages
        CHECK (initial_package IN ('HOURLY', 'OVERNIGHT', 'DAILY')
            AND applied_package IN ('HOURLY', 'OVERNIGHT', 'DAILY')
            AND max_package_reached IN ('HOURLY', 'OVERNIGHT', 'DAILY')),
    CONSTRAINT chk_rate_snapshot_transition
        CHECK (transition_reason IN (
            'INITIAL_QUOTE', 'HOURLY_WINDOW', 'OVERNIGHT_WINDOW',
            'DAILY_DURATION', 'PRICE_CAP', 'EXTENSION',
            'ACTUAL_CHECKOUT', 'ADMIN_APPROVED_ADJUSTMENT')),
    CONSTRAINT chk_rate_snapshot_interval
        CHECK (committed_check_out > committed_check_in
            AND (actual_check_out IS NULL OR actual_check_in IS NULL
                OR actual_check_out > actual_check_in)),
    CONSTRAINT chk_rate_snapshot_guest_counts
        CHECK (included_guests >= 1
            AND max_guests_snapshot >= included_guests
            AND line_guest_count >= 0
            AND room_quantity >= 1
            AND line_guest_count <= max_guests_snapshot * room_quantity
            AND extra_guest_count >= 0),
    CONSTRAINT chk_rate_snapshot_units
        CHECK (first_block_minutes >= 1
            AND extra_unit_minutes >= 1
            AND grace_minutes >= 0
            AND daily_duration_minutes >= 60
            AND full_days >= 0
            AND remainder_minutes >= 0
            AND charged_extra_units >= 0),
    CONSTRAINT chk_rate_snapshot_amounts
        CHECK (first_block_price >= 0
            AND extra_unit_price >= 0
            AND overnight_price >= 0
            AND daily_price >= 0
            AND minimum_committed_room_charge >= 0
            AND final_room_charge >= 0
            AND extra_guest_charge >= 0
            AND allocated_service_charge >= 0)
);

CREATE INDEX idx_rate_snapshot_line_created
    ON reservation_rate_snapshots(
        reservation_room_type_id, created_at_utc DESC);

CREATE INDEX idx_rate_snapshot_profile
    ON reservation_rate_snapshots(rate_profile_id);

INSERT INTO stay_policy_versions (
    policy_code,
    policy_version,
    grace_minutes,
    overnight_start_time,
    overnight_early_morning_end,
    overnight_hard_checkout_time,
    overnight_maximum_minutes,
    daily_threshold_minutes,
    daily_duration_minutes,
    turnover_buffer_minutes,
    inventory_protection_mode,
    effective_from_utc,
    active,
    created_at_utc
)
SELECT
    'DEFAULT_MOTEL_POLICY',
    1,
    15,
    TIME '20:00',
    TIME '06:00',
    TIME '12:00',
    720,
    1200,
    1440,
    30,
    'PACKAGE_ENTITLEMENT',
    TIMESTAMPTZ '2026-07-27 00:00:00+00',
    true,
    TIMESTAMPTZ '2026-07-27 00:00:00+00'
WHERE NOT EXISTS (
    SELECT 1
    FROM stay_policy_versions
    WHERE policy_code = 'DEFAULT_MOTEL_POLICY'
      AND policy_version = 1
);

CREATE OR REPLACE FUNCTION prevent_reservation_rate_snapshot_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'reservation_rate_snapshots is append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_reservation_rate_snapshots_append_only
BEFORE UPDATE OR DELETE OR TRUNCATE ON reservation_rate_snapshots
FOR EACH STATEMENT
EXECUTE FUNCTION prevent_reservation_rate_snapshot_mutation();

CREATE OR REPLACE FUNCTION protect_room_type_business_code()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.code IS DISTINCT FROM NEW.code
       AND (
           EXISTS (
               SELECT 1
               FROM reservation_room_types
               WHERE room_type_id = OLD.id
           )
           OR EXISTS (
               SELECT 1
               FROM room_rate_profiles
               WHERE room_type_id = OLD.id
           )
       ) THEN
        RAISE EXCEPTION
            'room_types.code is immutable after financial or reservation use'
            USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_room_types_protect_business_code
BEFORE UPDATE OF code ON room_types
FOR EACH ROW
EXECUTE FUNCTION protect_room_type_business_code();
