-- Pricing V2 Phase 2-3:
-- 1) correct only the untouched foundation seed's future effective date;
-- 2) enforce monotonic seed-compatible rate ordering;
-- 3) persist short-lived, immutable quote evidence for transactional revalidation.

ALTER TABLE stay_policy_versions
    DISABLE TRIGGER trg_stay_policy_versions_protect_version;

UPDATE stay_policy_versions
SET effective_from_utc = TIMESTAMPTZ '2026-01-01 00:00:00+00'
WHERE policy_code = 'DEFAULT_MOTEL_POLICY'
  AND policy_version = 1
  AND created_by_user_id IS NULL
  AND effective_from_utc = TIMESTAMPTZ '2026-07-27 00:00:00+00';

ALTER TABLE stay_policy_versions
    ENABLE TRIGGER trg_stay_policy_versions_protect_version;

ALTER TABLE room_rate_profiles
    DISABLE TRIGGER trg_room_rate_profiles_protect_version;

UPDATE room_rate_profiles
SET effective_from_utc = TIMESTAMPTZ '2026-01-01 00:00:00+00'
WHERE profile_version = 1
  AND created_by_user_id IS NULL
  AND effective_from_utc = TIMESTAMPTZ '2026-07-27 00:00:00+00'
  AND EXISTS (
      SELECT 1
      FROM room_types room_type
      WHERE room_type.id = room_rate_profiles.room_type_id
        AND room_type.code IN (
            'STANDARD', 'DELUXE', 'EXECUTIVE',
            'SUITE', 'FAMILY', 'PRESIDENTIAL'
        )
  );

ALTER TABLE room_rate_profiles
    ENABLE TRIGGER trg_room_rate_profiles_protect_version;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM room_rate_profiles
        WHERE first_block_price > overnight_price
           OR overnight_price > daily_price
    ) THEN
        RAISE EXCEPTION
            'Cannot enable Pricing V2: room rate package prices are not monotonic';
    END IF;
END;
$$;

ALTER TABLE room_rate_profiles
    ADD CONSTRAINT chk_room_rate_profile_monotonic_package_prices
        CHECK (first_block_price <= overnight_price
            AND overnight_price <= daily_price);

CREATE TABLE pricing_quotes (
    id uuid PRIMARY KEY,
    stay_policy_version_id bigint NOT NULL,
    pricing_algorithm_version varchar(32) NOT NULL,
    check_in timestamp(6) without time zone NOT NULL,
    check_out timestamp(6) without time zone NOT NULL,
    guest_count integer NOT NULL,
    room_charge decimal(14,2) NOT NULL,
    extra_guest_charge decimal(14,2) NOT NULL,
    service_charge decimal(14,2) NOT NULL,
    total_amount decimal(14,2) NOT NULL,
    inventory_protected_until timestamp(6) without time zone NOT NULL,
    request_hash char(64) NOT NULL,
    quote_hash char(64) NOT NULL,
    request_json jsonb NOT NULL,
    response_json jsonb NOT NULL,
    created_at_utc timestamp with time zone NOT NULL,
    expires_at_utc timestamp with time zone NOT NULL,
    CONSTRAINT fk_pricing_quote_policy
        FOREIGN KEY (stay_policy_version_id) REFERENCES stay_policy_versions(id),
    CONSTRAINT chk_pricing_quote_algorithm
        CHECK (pricing_algorithm_version = 'MOTEL_PACKAGE_V2'),
    CONSTRAINT chk_pricing_quote_interval
        CHECK (check_out > check_in
            AND inventory_protected_until >= check_out
            AND expires_at_utc > created_at_utc),
    CONSTRAINT chk_pricing_quote_guests
        CHECK (guest_count >= 1),
    CONSTRAINT chk_pricing_quote_amounts
        CHECK (room_charge >= 0
            AND extra_guest_charge >= 0
            AND service_charge >= 0
            AND total_amount = room_charge + extra_guest_charge + service_charge)
);

CREATE INDEX idx_pricing_quotes_expiry
    ON pricing_quotes(expires_at_utc);

CREATE INDEX idx_pricing_quotes_created
    ON pricing_quotes(created_at_utc DESC);

CREATE TABLE pricing_quote_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pricing_quote_id uuid NOT NULL,
    room_type_id bigint NOT NULL,
    rate_profile_id bigint NOT NULL,
    room_type_code_snapshot varchar(40) NOT NULL,
    rate_profile_version integer NOT NULL,
    room_quantity integer NOT NULL,
    line_guest_count integer NOT NULL,
    stay_classification varchar(24) NOT NULL,
    applied_package varchar(24) NOT NULL,
    transition_reason varchar(40) NOT NULL,
    package_included_checkout timestamp(6) without time zone NOT NULL,
    room_charge decimal(14,2) NOT NULL,
    extra_guest_charge decimal(14,2) NOT NULL,
    line_total_before_services decimal(14,2) NOT NULL,
    breakdown_json jsonb NOT NULL,
    CONSTRAINT uk_pricing_quote_room_type
        UNIQUE (pricing_quote_id, room_type_id),
    CONSTRAINT fk_pricing_quote_line_quote
        FOREIGN KEY (pricing_quote_id) REFERENCES pricing_quotes(id)
            ON DELETE CASCADE,
    CONSTRAINT fk_pricing_quote_line_room_type
        FOREIGN KEY (room_type_id) REFERENCES room_types(id),
    CONSTRAINT fk_pricing_quote_line_rate
        FOREIGN KEY (rate_profile_id) REFERENCES room_rate_profiles(id),
    CONSTRAINT chk_pricing_quote_line_values
        CHECK (rate_profile_version >= 1
            AND room_quantity >= 1
            AND line_guest_count >= 1
            AND room_charge >= 0
            AND extra_guest_charge >= 0
            AND line_total_before_services = room_charge + extra_guest_charge),
    CONSTRAINT chk_pricing_quote_line_classification
        CHECK (stay_classification IN ('DAY_STAY', 'NIGHT_STAY', 'MULTI_DAY')),
    CONSTRAINT chk_pricing_quote_line_package
        CHECK (applied_package IN ('HOURLY', 'OVERNIGHT', 'DAILY')),
    CONSTRAINT chk_pricing_quote_line_transition
        CHECK (transition_reason IN (
            'HOURLY_WINDOW', 'OVERNIGHT_WINDOW',
            'DAILY_DURATION', 'PRICE_CAP'))
);

CREATE INDEX idx_pricing_quote_lines_quote
    ON pricing_quote_lines(pricing_quote_id, id);

CREATE TABLE pricing_quote_commitments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pricing_quote_id uuid NOT NULL,
    reservation_id bigint NOT NULL,
    committed_at_utc timestamp with time zone NOT NULL,
    CONSTRAINT uk_pricing_quote_commitment_quote
        UNIQUE (pricing_quote_id),
    CONSTRAINT uk_pricing_quote_commitment_reservation
        UNIQUE (reservation_id),
    CONSTRAINT fk_pricing_quote_commitment_quote
        FOREIGN KEY (pricing_quote_id) REFERENCES pricing_quotes(id),
    CONSTRAINT fk_pricing_quote_commitment_reservation
        FOREIGN KEY (reservation_id) REFERENCES reservations(id)
);

CREATE OR REPLACE FUNCTION prevent_pricing_quote_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'pricing quote evidence is immutable'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_pricing_quotes_immutable
BEFORE UPDATE ON pricing_quotes
FOR EACH ROW
EXECUTE FUNCTION prevent_pricing_quote_update();

CREATE TRIGGER trg_pricing_quote_lines_immutable
BEFORE UPDATE ON pricing_quote_lines
FOR EACH ROW
EXECUTE FUNCTION prevent_pricing_quote_update();

CREATE OR REPLACE FUNCTION prevent_pricing_quote_commitment_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'pricing quote commitment evidence is append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_pricing_quote_commitments_append_only
BEFORE UPDATE OR DELETE OR TRUNCATE ON pricing_quote_commitments
FOR EACH STATEMENT
EXECUTE FUNCTION prevent_pricing_quote_commitment_mutation();
