-- PostgreSQL baseline for the hotel-management application schema.
-- Do not edit after applying to a shared environment.

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender varchar(255),
    session_id varchar(255),
    text text,
    timestamp TIMESTAMP(6) WITHOUT TIME ZONE,
    PRIMARY KEY (id)
);

CREATE TABLE contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    name varchar(150) NOT NULL,
    email varchar(255) NOT NULL,
    phone varchar(30),
    subject varchar(200) NOT NULL,
    message text NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'NEW',
    reply_subject varchar(200),
    reply_message text,
    replied_at TIMESTAMP(6) WITHOUT TIME ZONE,
    replied_by varchar(150),
    PRIMARY KEY (id)
);

CREATE TABLE customer_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    address text,
    email varchar(255),
    full_name varchar(255) NOT NULL,
    id_card_number varchar(50),
    phone varchar(20),
    source VARCHAR(32) NOT NULL,
    linked_user_id bigint,
    PRIMARY KEY (id),
    CONSTRAINT UKo9iw8255gp64srwu6yk2qm73q UNIQUE (linked_user_id)
);

CREATE TABLE facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    description text,
    description_en text,
    facility_name varchar(255),
    facility_name_en varchar(255),
    image_url varchar(500),
    type varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE galleries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    image_url varchar(500),
    title varchar(255),
    title_en varchar(255),
    type varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE group_has_role (
    group_id bigint NOT NULL,
    role_id bigint NOT NULL,
    PRIMARY KEY (group_id,role_id)
);

CREATE TABLE group_has_user (
    user_id bigint NOT NULL,
    group_id bigint NOT NULL,
    PRIMARY KEY (user_id,group_id)
);

CREATE TABLE guests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    checked_out_at TIMESTAMP(6) WITHOUT TIME ZONE,
    date_of_birth date,
    email varchar(255),
    full_name varchar(255) NOT NULL,
    id_card_number varchar(50),
    id_card_type VARCHAR(32),
    is_primary BOOLEAN,
    nationality varchar(255),
    phone varchar(20),
    reservation_room_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE idempotency_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_key varchar(128) NOT NULL,
    operation varchar(80) NOT NULL,
    actor_scope varchar(190) NOT NULL,
    request_hash char(64) NOT NULL,
    status varchar(32) NOT NULL,
    response_status int,
    response_json TEXT,
    resource_type varchar(80),
    resource_id varchar(255),
    expires_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    completed_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    created_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    version bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_idempotency_scope UNIQUE (request_key,operation,actor_scope),
    CONSTRAINT chk_idempotency_completed_response CHECK (((status <> 'COMPLETED') or (response_status is not null))),
    CONSTRAINT chk_idempotency_status CHECK ((status in ('PROCESSING','COMPLETED','FAILED')))
);

CREATE TABLE invalidated_tokens (
    token varchar(255) NOT NULL,
    expiry_time TIMESTAMP(6) WITHOUT TIME ZONE,
    reason varchar(50),
    PRIMARY KEY (token)
);

CREATE TABLE media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url varchar(500) NOT NULL,
    object_key varchar(500) NOT NULL,
    purpose varchar(32) NOT NULL,
    status varchar(32) NOT NULL,
    content_type varchar(100) NOT NULL,
    file_size bigint NOT NULL,
    width int,
    height int,
    uploaded_by_user_id bigint,
    owner_type varchar(32),
    owner_id bigint,
    claimed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    orphaned_at TIMESTAMP(6) WITHOUT TIME ZONE,
    deleted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    version bigint NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT uk_media_assets_url UNIQUE (url),
    CONSTRAINT uk_media_assets_object_key UNIQUE (object_key),
    CONSTRAINT uk_media_assets_owner UNIQUE (owner_type,owner_id)
);

CREATE TABLE oauth_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    provider varchar(32) NOT NULL,
    provider_subject varchar(255) NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_oauth_accounts_provider_subject UNIQUE (provider,provider_subject),
    CONSTRAINT uk_oauth_accounts_user_provider UNIQUE (user_id,provider)
);

CREATE TABLE payment_provider_events (
    id varchar(255) NOT NULL,
    provider varchar(20) NOT NULL,
    provider_event_id varchar(255) NOT NULL,
    provider_reference varchar(255),
    bank_reference_code varchar(255),
    provider_txn_id varchar(255),
    merchant_account_id varchar(128),
    dedup_key varchar(191) NOT NULL,
    payment_transaction_id varchar(255),
    status varchar(32) NOT NULL,
    payload_hash varchar(64) NOT NULL,
    transfer_type varchar(10),
    account_number_masked varchar(32),
    amount bigint,
    payment_code varchar(40),
    provider_occurred_at varchar(40),
    provider_occurred_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    received_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    processing_attempts int NOT NULL DEFAULT 0,
    next_retry_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    last_attempt_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    processed_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    last_error varchar(500),
    reviewed_by varchar(245),
    reviewed_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    review_note varchar(500),
    version bigint NOT NULL DEFAULT 0,
    message varchar(500),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT uk_provider_events_provider_event UNIQUE (provider,provider_event_id),
    CONSTRAINT uk_provider_events_provider_dedup UNIQUE (provider,dedup_key),
    CONSTRAINT uk_provider_events_provider_reference UNIQUE (provider,provider_reference)
);

CREATE TABLE payment_refunds (
    id varchar(255) NOT NULL,
    reservation_id bigint,
    provider_event_id varchar(255),
    completion_provider_event_id varchar(255),
    source_type varchar(32) NOT NULL DEFAULT 'LEGACY',
    source_key varchar(191),
    version bigint NOT NULL DEFAULT 0,
    payment_transaction_id varchar(255),
    provider varchar(20) NOT NULL,
    channel varchar(32) NOT NULL,
    status varchar(32) NOT NULL,
    recipient_id varchar(255),
    amount bigint NOT NULL,
    requested_amount bigint NOT NULL,
    actual_refund_amount bigint,
    request_id varchar(32) NOT NULL,
    refund_code varchar(64) NOT NULL,
    request_history varchar(1000),
    transaction_type varchar(2) NOT NULL,
    original_transaction_date varchar(14),
    provider_refund_txn_id varchar(255),
    response_code varchar(20),
    transaction_status varchar(20),
    completion_method varchar(32),
    manual_transfer_reference varchar(100),
    manual_transferred_by varchar(245),
    manual_transferred_at TIMESTAMP(6) WITHOUT TIME ZONE,
    manual_transferred_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    manual_fallback_available_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    manual_fallback_opened_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    manual_fallback_opened_by varchar(245),
    manual_fallback_reason varchar(255),
    proof_asset_id bigint,
    reason varchar(255),
    message varchar(500),
    requested_by varchar(245),
    requested_at TIMESTAMP(6) WITHOUT TIME ZONE,
    requested_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    completed_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    cancelled_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    cancelled_by varchar(245),
    cancellation_reason varchar(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT uk_payment_refunds_request_id UNIQUE (request_id),
    CONSTRAINT uk_payment_refunds_refund_code UNIQUE (refund_code),
    CONSTRAINT uk_payment_refunds_manual_transfer_reference UNIQUE (manual_transfer_reference),
    CONSTRAINT uk_payment_refunds_proof_asset UNIQUE (proof_asset_id),
    CONSTRAINT uk_payment_refunds_source_key UNIQUE (source_key),
    CONSTRAINT uk_payment_refunds_provider_event_source UNIQUE (provider_event_id,source_type),
    CONSTRAINT uk_payment_refunds_completion_event UNIQUE (completion_provider_event_id),
    CONSTRAINT chk_payment_refunds_source CHECK (((reservation_id is not null) or (payment_transaction_id is not null) or (provider_event_id is not null)))
);

CREATE TABLE payment_transactions (
    id varchar(255) NOT NULL,
    amount bigint NOT NULL,
    expected_amount bigint,
    received_amount bigint,
    accepted_amount bigint,
    refund_required_amount bigint,
    bank_code varchar(255),
    requested_bank_code varchar(20),
    provider_create_date varchar(14),
    provider_pay_date varchar(32),
    card_type varchar(20),
    card_token varchar(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    currency varchar(255) NOT NULL,
    ip_address varchar(255),
    message varchar(255),
    order_info varchar(255),
    paid_at TIMESTAMP(6) WITHOUT TIME ZONE,
    paid_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE,
    expires_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    provider varchar(20) NOT NULL,
    provider_txn_id varchar(255),
    provider_reference varchar(255),
    refund_txn_id varchar(255),
    response_code varchar(255),
    status VARCHAR(32) NOT NULL,
    txn_ref varchar(255) NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    reservation_id bigint NOT NULL,
    refund_amount bigint,
    refund_provider varchar(20),
    purpose varchar(32) NOT NULL DEFAULT 'FINAL_PAYMENT',
    refund_completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    version bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT UK4kqb40gqwn1nim0p5hgqdf2pf UNIQUE (txn_ref)
);

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    name varchar(100) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UKpnvtwliis6p05pn6i3ndjrqt2 UNIQUE (name)
);

CREATE TABLE reconciliation_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider varchar(32) NOT NULL,
    merchant_account_id varchar(255) NOT NULL,
    cursor_value varchar(512),
    last_successful_occurred_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    last_run_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    last_error text,
    created_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    version bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_reconciliation_provider_account UNIQUE (provider,merchant_account_id)
);

CREATE TABLE refund_recipients (
    id varchar(255) NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    reservation_id bigint,
    payment_refund_id varchar(255),
    method varchar(32) NOT NULL,
    bank_code varchar(20) NOT NULL,
    bank_name varchar(120) NOT NULL,
    account_number_ciphertext varchar(1000) NOT NULL,
    account_number_last4 varchar(4) NOT NULL,
    account_holder_ciphertext varchar(1000) NOT NULL,
    encryption_key_version varchar(20) NOT NULL,
    status varchar(32) NOT NULL,
    provided_by varchar(245) NOT NULL,
    provided_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    verified_by varchar(245),
    verified_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT uk_refund_recipients_payment_refund UNIQUE (payment_refund_id)
);

CREATE TABLE reservation_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reservation_id bigint,
    reservation_code varchar(50),
    target_type varchar(64),
    target_id varchar(255),
    action varchar(40) NOT NULL,
    action_code varchar(80),
    actor_user_id bigint,
    actor_name varchar(150) NOT NULL,
    actor_role varchar(32) NOT NULL,
    correlation_id varchar(128),
    details text,
    metadata_json TEXT,
    occurred_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    PRIMARY KEY (id)
);

CREATE TABLE reservation_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    created_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    invoice_number varchar(64) NOT NULL,
    issued_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    issued_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    snapshot_json TEXT NOT NULL,
    snapshot_hash char(64),
    snapshot_created_at_utc TIMESTAMP(6) WITH TIME ZONE NULL,
    total_amount decimal(19,2) NOT NULL,
    currency char(3) NOT NULL DEFAULT 'VND',
    room_charge decimal(19,2),
    actual_room_charge decimal(19,2),
    planned_room_charge decimal(19,2),
    early_checkout_adjustment decimal(19,2),
    late_checkout_fee decimal(19,2),
    additional_fee decimal(19,2),
    discount_amount decimal(19,2),
    tax_amount decimal(19,2),
    gross_received_amount bigint,
    accepted_paid_amount bigint,
    refunded_amount bigint,
    completed_refund_amount bigint,
    balance_amount bigint,
    remaining_amount bigint,
    settlement_status varchar(32),
    reservation_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT idx_invoice_number UNIQUE (invoice_number),
    CONSTRAINT UK4jb76632pkjrr0t4972cjk2bc UNIQUE (reservation_id)
);

CREATE TABLE reservation_room_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    quantity int NOT NULL,
    room_price decimal(12,2) NOT NULL,
    subtotal decimal(12,2) NOT NULL,
    reservation_id bigint NOT NULL,
    room_type_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE reservation_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    status varchar(20) NOT NULL DEFAULT 'PENDING_ASSIGN',
    assigned_by bigint,
    reservation_room_type_id bigint NOT NULL,
    room_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    actual_check_in TIMESTAMP(6) WITHOUT TIME ZONE,
    actual_check_out TIMESTAMP(6) WITHOUT TIME ZONE,
    last_activity_at TIMESTAMP(6) WITHOUT TIME ZONE,
    cancellation_reason text,
    cancellation_reason_code varchar(64),
    check_in TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    check_out TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    discount_amount decimal(12,2) NOT NULL,
    guest_count int,
    guest_token varchar(64),
    late_checkout_fee decimal(12,2) NOT NULL,
    note text,
    reservation_code varchar(50) NOT NULL,
    status varchar(32) NOT NULL,
    tax_amount decimal(12,2) NOT NULL,
    total_amount decimal(12,2) NOT NULL,
    payment_plan varchar(24) NOT NULL DEFAULT 'DEPOSIT_50',
    required_initial_payment decimal(12,2) NOT NULL,
    customer_profile_id bigint NOT NULL,
    cancellation_fee decimal(12,2) NOT NULL,
    refundable_amount decimal(12,2) NOT NULL,
    status_before_cancellation varchar(32),
    early_checkout_adjustment decimal(12,2) NOT NULL,
    checkout_additional_fee decimal(12,2) NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT UK6g1uj544xgjuyhj6kjh6pka6l UNIQUE (reservation_code),
    CONSTRAINT UK9kbktsq5pr0h5hyqiqimvm8q0 UNIQUE (guest_token)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    comment text,
    rating int NOT NULL,
    reservation_id bigint NOT NULL,
    room_type_id bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_review_user_reservation_room_type UNIQUE (user_id,reservation_id,room_type_id),
    CONSTRAINT reviews_chk_1 CHECK (((rating <= 5) and (rating >= 1)))
);

CREATE TABLE role_has_permission (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    PRIMARY KEY (role_id,permission_id)
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    name varchar(50) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UKofx66keruapi6vyqpv6f2or37 UNIQUE (name)
);

CREATE TABLE room_holds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    reservation_room_type_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UKk37e3w8x2ijfkjxsihv3gfmtj UNIQUE (reservation_room_type_id)
);

CREATE TABLE room_maintenance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    action varchar(100) NOT NULL,
    note text NOT NULL,
    room_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE room_type_facilities (
    room_type_id bigint NOT NULL,
    facility_id bigint NOT NULL,
    PRIMARY KEY (room_type_id,facility_id)
);

CREATE TABLE room_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    description text,
    description_en text,
    image_url varchar(500),
    price decimal(12,2),
    type_name varchar(100),
    type_name_en varchar(100),
    max_guests int NOT NULL DEFAULT '2',
    PRIMARY KEY (id)
);

CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    cleaning_status VARCHAR(32),
    description text,
    floor int,
    room_name varchar(20),
    status VARCHAR(32),
    sellable BOOLEAN NOT NULL DEFAULT '1',
    decommissioned_at TIMESTAMP(6) WITHOUT TIME ZONE,
    room_type_id bigint,
    maintenance_expected_completed_date date,
    maintenance_reason text,
    PRIMARY KEY (id),
    CONSTRAINT UK36daphag00mnxmwforqperdnb UNIQUE (room_name)
);

CREATE TABLE tbl_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    name varchar(100) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UKp4yaoo44agqma8unhiyjnvbns UNIQUE (name)
);

CREATE TABLE user_tokens (
    user_id bigint NOT NULL,
    access_token varchar(500),
    access_token_expires_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    refresh_token varchar(500) NOT NULL,
    refresh_token_expires_at TIMESTAMP(6) WITHOUT TIME ZONE,
    PRIMARY KEY (user_id)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    address text,
    email varchar(255) NOT NULL,
    email_verified BOOLEAN NOT NULL,
    full_name varchar(255) NOT NULL,
    image_url varchar(500),
    password varchar(255),
    phone varchar(255),
    status VARCHAR(32),
    type VARCHAR(32),
    username varchar(255) NOT NULL,
    verification_code varchar(255),
    password_reset_token_hash varchar(64),
    password_reset_expires_at TIMESTAMP(6) WITHOUT TIME ZONE,
    verification_expires_at TIMESTAMP(6) WITHOUT TIME ZONE,
    security_version bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT UK6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT UKr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
    CONSTRAINT UKdu5v5sr43g5bfnji4vb8hg5s3 UNIQUE (phone),
    CONSTRAINT uk_users_password_reset_token_hash UNIQUE (password_reset_token_hash)
);

CREATE INDEX idx_contact_messages_status_created ON contact_messages (status,created_at);
CREATE INDEX idx_customer_profile_phone ON customer_profiles (phone);
CREATE INDEX idx_customer_profile_email ON customer_profiles (email);
CREATE INDEX idx_customer_profile_id_card ON customer_profiles (id_card_number);
CREATE INDEX FK5ayf1jgw937kcflrhnugtg2xh ON group_has_role (role_id);
CREATE INDEX FKjv6m9vvc8etoiclfvgnalh3hr ON group_has_user (group_id);
CREATE INDEX FKe29g4uv5q14pn3v8togaxgj03 ON guests (reservation_room_id);
CREATE INDEX idx_idempotency_expiry ON idempotency_requests (expires_at_utc);
CREATE INDEX idx_idempotency_status_updated ON idempotency_requests (status,updated_at_utc);
CREATE INDEX idx_idempotency_resource ON idempotency_requests (resource_type,resource_id);
CREATE INDEX idx_media_assets_status_created ON media_assets (status,created_at);
CREATE INDEX idx_media_assets_status_orphaned ON media_assets (status,orphaned_at);
CREATE INDEX idx_media_assets_uploader ON media_assets (uploaded_by_user_id);
CREATE INDEX idx_oauth_accounts_user_id ON oauth_accounts (user_id);
CREATE INDEX idx_provider_events_payment ON payment_provider_events (payment_transaction_id);
CREATE INDEX idx_provider_events_status_created ON payment_provider_events (status,created_at);
CREATE INDEX idx_provider_events_provider_txn ON payment_provider_events (provider,provider_txn_id);
CREATE INDEX idx_provider_events_retry ON payment_provider_events (status,next_retry_at_utc,created_at);
CREATE INDEX idx_payment_refunds_status ON payment_refunds (status);
CREATE INDEX idx_payment_refunds_payment ON payment_refunds (payment_transaction_id);
CREATE INDEX idx_payment_refunds_channel_status ON payment_refunds (channel,status);
CREATE INDEX idx_payment_refunds_recipient ON payment_refunds (recipient_id);
CREATE INDEX idx_payment_refunds_reservation_source ON payment_refunds (reservation_id,source_type);
CREATE INDEX idx_payment_refunds_provider_event ON payment_refunds (provider_event_id);
CREATE INDEX idx_payment_refunds_obligation ON payment_refunds (payment_transaction_id,source_type,status);
CREATE INDEX idx_payment_refunds_auto_wait ON payment_refunds (channel,status,manual_fallback_available_at_utc);
CREATE INDEX FK6lysm563jhpge8piv14tglqqx ON payment_transactions (reservation_id);
CREATE INDEX idx_payment_transactions_provider_status_created ON payment_transactions (provider,status,created_at);
CREATE INDEX idx_payments_allocation_review ON payment_transactions (status,accepted_amount,created_at);
CREATE INDEX idx_reconciliation_last_run ON reconciliation_state (last_run_at_utc);
CREATE INDEX idx_refund_recipients_reservation ON refund_recipients (reservation_id);
CREATE INDEX idx_refund_recipients_status ON refund_recipients (status);
CREATE INDEX idx_refund_recipients_payment_refund ON refund_recipients (payment_refund_id);
CREATE INDEX idx_reservation_audit_reservation_created ON reservation_audit_logs (reservation_id,created_at);
CREATE INDEX idx_audit_target_created ON reservation_audit_logs (target_type,target_id,created_at);
CREATE INDEX idx_audit_action_code ON reservation_audit_logs (action_code);
CREATE INDEX idx_audit_correlation ON reservation_audit_logs (correlation_id);
CREATE INDEX idx_invoice_settlement_status ON reservation_invoices (settlement_status);
CREATE INDEX idx_invoice_snapshot_hash ON reservation_invoices (snapshot_hash);
CREATE INDEX FK8lfgyecs06xlni10u8xs7a7fy ON reservation_room_types (reservation_id);
CREATE INDEX FK5hoacrg2vv4p92ipxkqx588uk ON reservation_room_types (room_type_id);
CREATE INDEX FKjxjtc4mikk2upyppl46dxxt60 ON reservation_rooms (assigned_by);
CREATE INDEX FKe1fabohk3l28aa110p6kayr7y ON reservation_rooms (reservation_room_type_id);
CREATE INDEX FK81imhuuxynjj2ivy82koy38nm ON reservation_rooms (room_id);
CREATE INDEX FKs0a3i3b28ytn37gc1wmakiyjg ON reservations (customer_profile_id);
CREATE INDEX idx_reservations_last_activity ON reservations (last_activity_at);
CREATE INDEX idx_reservations_cancellation_reason_code ON reservations (cancellation_reason_code);
CREATE INDEX idx_review_room_type ON reviews (room_type_id);
CREATE INDEX idx_review_reservation ON reviews (reservation_id);
CREATE INDEX FK4tkb5h6g9725voio02abkw8cq ON role_has_permission (permission_id);
CREATE INDEX idx_room_hold_reservation_room_type ON room_holds (reservation_room_type_id);
CREATE INDEX idx_room_hold_status ON room_holds (status);
CREATE INDEX idx_room_hold_expires_at ON room_holds (expires_at);
CREATE INDEX FK398jg0ax4snlkrd61uwiukwjq ON room_maintenance_logs (room_id);
CREATE INDEX FK3x6quqddcy358kvmjjc9d53vx ON room_type_facilities (facility_id);
CREATE INDEX FKh9m2n1paq5hmd3u0klfl7wsfv ON rooms (room_type_id);
CREATE INDEX idx_rooms_sellable_status ON rooms (sellable,status);

ALTER TABLE customer_profiles ADD CONSTRAINT FKkcopmxblq64tiq942bu3k2rna FOREIGN KEY (linked_user_id) REFERENCES users (id);
ALTER TABLE group_has_role ADD CONSTRAINT FK5ayf1jgw937kcflrhnugtg2xh FOREIGN KEY (role_id) REFERENCES roles (id);
ALTER TABLE group_has_role ADD CONSTRAINT FKsvenjxg4p96l9p4qvlwmaak43 FOREIGN KEY (group_id) REFERENCES tbl_groups (id);
ALTER TABLE group_has_user ADD CONSTRAINT FKhr5ypg2t7gd3huwgl4tijtx4l FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE group_has_user ADD CONSTRAINT FKjv6m9vvc8etoiclfvgnalh3hr FOREIGN KEY (group_id) REFERENCES tbl_groups (id);
ALTER TABLE guests ADD CONSTRAINT FKe29g4uv5q14pn3v8togaxgj03 FOREIGN KEY (reservation_room_id) REFERENCES reservation_rooms (id);
ALTER TABLE media_assets ADD CONSTRAINT fk_media_assets_uploader FOREIGN KEY (uploaded_by_user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE oauth_accounts ADD CONSTRAINT fk_oauth_accounts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE payment_provider_events ADD CONSTRAINT fk_provider_events_payment FOREIGN KEY (payment_transaction_id) REFERENCES payment_transactions (id);
ALTER TABLE payment_refunds ADD CONSTRAINT fk_payment_refunds_completion_event FOREIGN KEY (completion_provider_event_id) REFERENCES payment_provider_events (id);
ALTER TABLE payment_refunds ADD CONSTRAINT fk_payment_refunds_payment FOREIGN KEY (payment_transaction_id) REFERENCES payment_transactions (id);
ALTER TABLE payment_refunds ADD CONSTRAINT fk_payment_refunds_proof_asset FOREIGN KEY (proof_asset_id) REFERENCES media_assets (id) ON DELETE RESTRICT;
ALTER TABLE payment_refunds ADD CONSTRAINT fk_payment_refunds_provider_event FOREIGN KEY (provider_event_id) REFERENCES payment_provider_events (id);
ALTER TABLE payment_refunds ADD CONSTRAINT fk_payment_refunds_recipient FOREIGN KEY (recipient_id) REFERENCES refund_recipients (id);
ALTER TABLE payment_refunds ADD CONSTRAINT fk_payment_refunds_reservation FOREIGN KEY (reservation_id) REFERENCES reservations (id);
ALTER TABLE payment_transactions ADD CONSTRAINT FK6lysm563jhpge8piv14tglqqx FOREIGN KEY (reservation_id) REFERENCES reservations (id);
ALTER TABLE refund_recipients ADD CONSTRAINT fk_refund_recipients_payment_refund FOREIGN KEY (payment_refund_id) REFERENCES payment_refunds (id);
ALTER TABLE refund_recipients ADD CONSTRAINT fk_refund_recipients_reservation FOREIGN KEY (reservation_id) REFERENCES reservations (id);
ALTER TABLE reservation_invoices ADD CONSTRAINT FKdfdk5a9v3x5yjf6l1vxhpg9xv FOREIGN KEY (reservation_id) REFERENCES reservations (id);
ALTER TABLE reservation_room_types ADD CONSTRAINT FK5hoacrg2vv4p92ipxkqx588uk FOREIGN KEY (room_type_id) REFERENCES room_types (id);
ALTER TABLE reservation_room_types ADD CONSTRAINT FK8lfgyecs06xlni10u8xs7a7fy FOREIGN KEY (reservation_id) REFERENCES reservations (id);
ALTER TABLE reservation_rooms ADD CONSTRAINT FK81imhuuxynjj2ivy82koy38nm FOREIGN KEY (room_id) REFERENCES rooms (id);
ALTER TABLE reservation_rooms ADD CONSTRAINT FKe1fabohk3l28aa110p6kayr7y FOREIGN KEY (reservation_room_type_id) REFERENCES reservation_room_types (id);
ALTER TABLE reservation_rooms ADD CONSTRAINT FKjxjtc4mikk2upyppl46dxxt60 FOREIGN KEY (assigned_by) REFERENCES users (id);
ALTER TABLE reservations ADD CONSTRAINT FKs0a3i3b28ytn37gc1wmakiyjg FOREIGN KEY (customer_profile_id) REFERENCES customer_profiles (id);
ALTER TABLE reviews ADD CONSTRAINT FK4mjgyh1vc99vaf9l18j2ejc89 FOREIGN KEY (reservation_id) REFERENCES reservations (id);
ALTER TABLE reviews ADD CONSTRAINT FKcgy7qjc1r99dp117y9en6lxye FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE reviews ADD CONSTRAINT FKrsky1fnfdmm2chhfxvivf67hx FOREIGN KEY (room_type_id) REFERENCES room_types (id);
ALTER TABLE role_has_permission ADD CONSTRAINT FK4tkb5h6g9725voio02abkw8cq FOREIGN KEY (permission_id) REFERENCES permissions (id);
ALTER TABLE role_has_permission ADD CONSTRAINT FKl5t2ucrudh92ach6bddb918kp FOREIGN KEY (role_id) REFERENCES roles (id);
ALTER TABLE room_holds ADD CONSTRAINT FKd8u26kdadc9mvp2ks95263pll FOREIGN KEY (reservation_room_type_id) REFERENCES reservation_room_types (id);
ALTER TABLE room_maintenance_logs ADD CONSTRAINT FK398jg0ax4snlkrd61uwiukwjq FOREIGN KEY (room_id) REFERENCES rooms (id);
ALTER TABLE room_type_facilities ADD CONSTRAINT FK3x6quqddcy358kvmjjc9d53vx FOREIGN KEY (facility_id) REFERENCES facilities (id);
ALTER TABLE room_type_facilities ADD CONSTRAINT FKhegiykepjecgokfw7rwqjlhnj FOREIGN KEY (room_type_id) REFERENCES room_types (id);
ALTER TABLE rooms ADD CONSTRAINT FKh9m2n1paq5hmd3u0klfl7wsfv FOREIGN KEY (room_type_id) REFERENCES room_types (id);
