-- Operational cash accountability. This migration is additive: existing
-- payment/refund rows are not rewritten or guessed into historical shifts.

CREATE TABLE cashier_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    shift_code VARCHAR(48) NOT NULL,
    business_date DATE NOT NULL,
    status VARCHAR(16) NOT NULL,
    opened_by BIGINT NOT NULL,
    opened_by_name VARCHAR(150) NOT NULL,
    opened_by_role VARCHAR(32) NOT NULL,
    opened_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    closed_by BIGINT,
    closed_by_name VARCHAR(150),
    closed_by_role VARCHAR(32),
    closed_at_utc TIMESTAMP(6) WITH TIME ZONE,
    opening_cash_amount NUMERIC(19,0) NOT NULL,
    expected_cash_amount NUMERIC(19,0),
    counted_cash_amount NUMERIC(19,0),
    variance_amount NUMERIC(19,0),
    note VARCHAR(1000),
    close_note VARCHAR(1000),
    created_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_cashier_shift_code UNIQUE (shift_code),
    CONSTRAINT fk_cashier_shift_opened_by FOREIGN KEY (opened_by) REFERENCES users (id),
    CONSTRAINT fk_cashier_shift_closed_by FOREIGN KEY (closed_by) REFERENCES users (id),
    CONSTRAINT chk_cashier_shift_status
        CHECK (status IN ('OPEN', 'CLOSING', 'CLOSED', 'CANCELLED')),
    CONSTRAINT chk_cashier_shift_opening_cash CHECK (opening_cash_amount >= 0),
    CONSTRAINT chk_cashier_shift_expected_cash
        CHECK (expected_cash_amount IS NULL OR expected_cash_amount >= 0),
    CONSTRAINT chk_cashier_shift_counted_cash
        CHECK (counted_cash_amount IS NULL OR counted_cash_amount >= 0),
    CONSTRAINT chk_cashier_shift_close_state CHECK (
        (status IN ('OPEN', 'CLOSING') AND closed_at_utc IS NULL)
        OR (status IN ('CLOSED', 'CANCELLED') AND closed_at_utc IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uk_cashier_shift_active_user
    ON cashier_shifts (opened_by)
    WHERE status IN ('OPEN', 'CLOSING');

CREATE INDEX idx_cashier_shift_business_date
    ON cashier_shifts (business_date DESC, opened_at_utc DESC, id DESC);

CREATE INDEX idx_cashier_shift_status_opened
    ON cashier_shifts (status, opened_at_utc, id);

CREATE TABLE cash_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cashier_shift_id BIGINT NOT NULL,
    movement_type VARCHAR(32) NOT NULL,
    direction VARCHAR(8) NOT NULL,
    amount NUMERIC(19,0) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id VARCHAR(191) NOT NULL,
    reservation_id BIGINT,
    payment_transaction_id VARCHAR(255),
    refund_id VARCHAR(255),
    created_by BIGINT NOT NULL,
    created_by_name VARCHAR(150) NOT NULL,
    created_by_role VARCHAR(32) NOT NULL,
    reason VARCHAR(500),
    occurred_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_cash_movement_shift
        FOREIGN KEY (cashier_shift_id) REFERENCES cashier_shifts (id),
    CONSTRAINT fk_cash_movement_reservation
        FOREIGN KEY (reservation_id) REFERENCES reservations (id),
    CONSTRAINT fk_cash_movement_payment
        FOREIGN KEY (payment_transaction_id) REFERENCES payment_transactions (id),
    CONSTRAINT fk_cash_movement_refund
        FOREIGN KEY (refund_id) REFERENCES payment_refunds (id),
    CONSTRAINT fk_cash_movement_created_by
        FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT uk_cash_movement_source
        UNIQUE (source_type, source_id, movement_type),
    CONSTRAINT chk_cash_movement_type CHECK (
        movement_type IN ('OPENING_FLOAT', 'CASH_PAYMENT', 'CASH_REFUND',
                          'CASH_IN', 'CASH_OUT', 'ADJUSTMENT')
    ),
    CONSTRAINT chk_cash_movement_direction CHECK (direction IN ('IN', 'OUT')),
    CONSTRAINT chk_cash_movement_amount CHECK (amount > 0),
    CONSTRAINT chk_cash_movement_source_type CHECK (
        source_type IN ('CASHIER_SHIFT', 'PAYMENT_TRANSACTION',
                        'PAYMENT_REFUND', 'MANUAL')
    ),
    CONSTRAINT chk_cash_movement_direction_type CHECK (
        (movement_type IN ('OPENING_FLOAT', 'CASH_PAYMENT', 'CASH_IN') AND direction = 'IN')
        OR (movement_type IN ('CASH_REFUND', 'CASH_OUT') AND direction = 'OUT')
        OR movement_type = 'ADJUSTMENT'
    )
);

CREATE INDEX idx_cash_movement_shift_occurred
    ON cash_movements (cashier_shift_id, occurred_at_utc, id);

CREATE INDEX idx_cash_movement_reservation
    ON cash_movements (reservation_id, occurred_at_utc DESC, id DESC)
    WHERE reservation_id IS NOT NULL;

CREATE OR REPLACE FUNCTION prevent_cash_movement_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'cash_movements is append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_cash_movements_append_only
BEFORE UPDATE OR DELETE OR TRUNCATE ON cash_movements
FOR EACH STATEMENT
EXECUTE FUNCTION prevent_cash_movement_mutation();

CREATE OR REPLACE FUNCTION protect_closed_cashier_shift()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'cashier_shifts cannot be deleted'
            USING ERRCODE = '55000';
    END IF;
    IF OLD.status IN ('CLOSED', 'CANCELLED') THEN
        RAISE EXCEPTION 'closed cashier_shifts are immutable'
            USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_cashier_shift_protect_closed
BEFORE UPDATE OR DELETE ON cashier_shifts
FOR EACH ROW
EXECUTE FUNCTION protect_closed_cashier_shift();

CREATE TRIGGER trg_cashier_shifts_no_truncate
BEFORE TRUNCATE ON cashier_shifts
FOR EACH STATEMENT
EXECUTE FUNCTION prevent_cash_movement_mutation();
