-- Compact operational journal and immutable business-day close. Historical
-- payment/refund/invoice data is deliberately not backfilled or guessed.

CREATE TABLE business_day_close_locks (
    business_date DATE NOT NULL,
    created_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (business_date)
);

CREATE TABLE financial_journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entry_number VARCHAR(64) NOT NULL,
    business_date DATE NOT NULL,
    original_business_date DATE NOT NULL,
    occurred_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    posted_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id VARCHAR(255) NOT NULL,
    posting_kind VARCHAR(32) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    description VARCHAR(500) NOT NULL,
    late_posting BOOLEAN NOT NULL DEFAULT FALSE,
    total_debit NUMERIC(19,0) NOT NULL,
    total_credit NUMERIC(19,0) NOT NULL,
    detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    reservation_id BIGINT,
    payment_transaction_id VARCHAR(255),
    refund_id VARCHAR(255),
    invoice_id BIGINT,
    provider_event_id VARCHAR(255),
    reversal_of_entry_id BIGINT,
    created_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_financial_journal_entry_number UNIQUE (entry_number),
    CONSTRAINT uk_financial_journal_source UNIQUE (source_type, source_id, posting_kind),
    CONSTRAINT fk_financial_journal_reservation FOREIGN KEY (reservation_id) REFERENCES reservations (id),
    CONSTRAINT fk_financial_journal_payment FOREIGN KEY (payment_transaction_id) REFERENCES payment_transactions (id),
    CONSTRAINT fk_financial_journal_refund FOREIGN KEY (refund_id) REFERENCES payment_refunds (id),
    CONSTRAINT fk_financial_journal_invoice FOREIGN KEY (invoice_id) REFERENCES reservation_invoices (id),
    CONSTRAINT fk_financial_journal_provider_event FOREIGN KEY (provider_event_id) REFERENCES payment_provider_events (id),
    CONSTRAINT fk_financial_journal_reversal FOREIGN KEY (reversal_of_entry_id) REFERENCES financial_journal_entries (id),
    CONSTRAINT chk_financial_journal_source_type CHECK (source_type IN (
        'PAYMENT_TRANSACTION', 'PAYMENT_REFUND', 'RESERVATION_INVOICE', 'PAYMENT_PROVIDER_EVENT')),
    CONSTRAINT chk_financial_journal_posting_kind CHECK (posting_kind IN (
        'PAYMENT_RECEIVED', 'REFUND_COMPLETED', 'INVOICE_RECOGNIZED',
        'PROVIDER_CASH_OBSERVED', 'PAYMENT_ALLOCATED', 'REFUND_ALLOCATED', 'REVERSAL')),
    CONSTRAINT chk_financial_journal_currency CHECK (currency = 'VND'),
    CONSTRAINT chk_financial_journal_totals CHECK (
        total_debit >= 0 AND total_credit >= 0 AND total_debit = total_credit),
    CONSTRAINT chk_financial_journal_reversal CHECK (
        (posting_kind = 'REVERSAL' AND reversal_of_entry_id IS NOT NULL)
        OR (posting_kind <> 'REVERSAL' AND reversal_of_entry_id IS NULL))
);

CREATE INDEX idx_financial_journal_business_date
    ON financial_journal_entries (business_date DESC, posted_at_utc DESC, id DESC);
CREATE INDEX idx_financial_journal_original_date
    ON financial_journal_entries (original_business_date DESC, occurred_at_utc DESC, id DESC);
CREATE INDEX idx_financial_journal_reservation
    ON financial_journal_entries (reservation_id, posted_at_utc DESC, id DESC)
    WHERE reservation_id IS NOT NULL;

CREATE TABLE financial_journal_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    journal_entry_id BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    account_code VARCHAR(32) NOT NULL,
    direction VARCHAR(8) NOT NULL,
    amount NUMERIC(19,0) NOT NULL,
    description VARCHAR(500),
    created_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_financial_journal_line_entry FOREIGN KEY (journal_entry_id)
        REFERENCES financial_journal_entries (id),
    CONSTRAINT uk_financial_journal_line_number UNIQUE (journal_entry_id, line_number),
    CONSTRAINT chk_financial_journal_account CHECK (account_code IN (
        'CASH_ON_HAND', 'BANK_SEPAY', 'CUSTOMER_DEPOSIT', 'REFUND_PAYABLE',
        'ROOM_REVENUE', 'SERVICE_REVENUE', 'DISCOUNT', 'TAX_PAYABLE',
        'UNRECONCILED_FUNDS')),
    CONSTRAINT chk_financial_journal_direction CHECK (direction IN ('DEBIT', 'CREDIT')),
    CONSTRAINT chk_financial_journal_line_amount CHECK (amount > 0)
);

CREATE INDEX idx_financial_journal_line_account
    ON financial_journal_lines (account_code, journal_entry_id);

CREATE TABLE business_day_closes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    business_date DATE NOT NULL,
    status VARCHAR(16) NOT NULL,
    closed_by BIGINT NOT NULL,
    closed_by_name VARCHAR(150) NOT NULL,
    closed_by_role VARCHAR(32) NOT NULL,
    closed_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    journal_entry_count BIGINT NOT NULL,
    total_debit NUMERIC(19,0) NOT NULL,
    total_credit NUMERIC(19,0) NOT NULL,
    payment_received_amount NUMERIC(19,0) NOT NULL,
    refund_completed_amount NUMERIC(19,0) NOT NULL,
    recognized_revenue_amount NUMERIC(19,0) NOT NULL,
    pending_refund_payable_amount NUMERIC(19,0) NOT NULL,
    cash_variance_amount NUMERIC(19,0) NOT NULL,
    summary_json JSONB NOT NULL,
    summary_hash VARCHAR(64) NOT NULL,
    note VARCHAR(1000),
    created_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_business_day_close_date UNIQUE (business_date),
    CONSTRAINT fk_business_day_close_user FOREIGN KEY (closed_by) REFERENCES users (id),
    CONSTRAINT chk_business_day_close_status CHECK (status = 'CLOSED'),
    CONSTRAINT chk_business_day_close_totals CHECK (
        journal_entry_count >= 0 AND total_debit >= 0 AND total_credit >= 0
        AND total_debit = total_credit
        AND payment_received_amount >= 0 AND refund_completed_amount >= 0
        AND recognized_revenue_amount >= 0 AND pending_refund_payable_amount >= 0)
);

CREATE INDEX idx_business_day_close_closed_at
    ON business_day_closes (closed_at_utc DESC, business_date DESC);

CREATE OR REPLACE FUNCTION prevent_posting_to_closed_business_day()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    entry_business_date DATE;
BEGIN
    IF TG_TABLE_NAME = 'financial_journal_entries' THEN
        entry_business_date := NEW.business_date;
    ELSE
        SELECT business_date INTO entry_business_date
        FROM financial_journal_entries
        WHERE id = NEW.journal_entry_id;
    END IF;

    IF EXISTS (
        SELECT 1 FROM business_day_closes
        WHERE business_date = entry_business_date
    ) THEN
        RAISE EXCEPTION 'business day % is closed', entry_business_date
            USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_financial_journal_entry_open_day
BEFORE INSERT ON financial_journal_entries
FOR EACH ROW EXECUTE FUNCTION prevent_posting_to_closed_business_day();

CREATE TRIGGER trg_financial_journal_line_open_day
BEFORE INSERT ON financial_journal_lines
FOR EACH ROW EXECUTE FUNCTION prevent_posting_to_closed_business_day();

CREATE OR REPLACE FUNCTION prevent_financial_journal_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'financial journal is append-only'
        USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER trg_financial_journal_entries_append_only
BEFORE UPDATE OR DELETE OR TRUNCATE ON financial_journal_entries
FOR EACH STATEMENT EXECUTE FUNCTION prevent_financial_journal_mutation();

CREATE TRIGGER trg_financial_journal_lines_append_only
BEFORE UPDATE OR DELETE OR TRUNCATE ON financial_journal_lines
FOR EACH STATEMENT EXECUTE FUNCTION prevent_financial_journal_mutation();

CREATE TRIGGER trg_business_day_closes_append_only
BEFORE UPDATE OR DELETE OR TRUNCATE ON business_day_closes
FOR EACH STATEMENT EXECUTE FUNCTION prevent_financial_journal_mutation();
