-- Staff work scheduling and attendance linked atomically to cashier shifts.
-- Scheduled timestamps are snapshotted in UTC so later edits to a shift
-- template never rewrite historical attendance.

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE work_shift_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    code VARCHAR(32) NOT NULL,
    name VARCHAR(100) NOT NULL,
    start_time TIME WITHOUT TIME ZONE NOT NULL,
    end_time TIME WITHOUT TIME ZONE NOT NULL,
    check_in_early_minutes INTEGER NOT NULL DEFAULT 30,
    late_tolerance_minutes INTEGER NOT NULL DEFAULT 15,
    color VARCHAR(7) NOT NULL DEFAULT '#0F2A43',
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_work_shift_template_code UNIQUE (code),
    CONSTRAINT chk_work_shift_template_code
        CHECK (code = upper(trim(code)) AND code <> ''),
    CONSTRAINT chk_work_shift_template_name
        CHECK (trim(name) <> ''),
    CONSTRAINT chk_work_shift_template_time
        CHECK (start_time <> end_time),
    CONSTRAINT chk_work_shift_template_early
        CHECK (check_in_early_minutes BETWEEN 0 AND 240),
    CONSTRAINT chk_work_shift_template_late
        CHECK (late_tolerance_minutes BETWEEN 0 AND 240),
    CONSTRAINT chk_work_shift_template_color
        CHECK (color ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE TABLE work_schedule_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    employee_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    employee_name_snapshot VARCHAR(150) NOT NULL,
    shift_template_id BIGINT NOT NULL REFERENCES work_shift_templates(id) ON DELETE RESTRICT,
    shift_code_snapshot VARCHAR(32) NOT NULL,
    shift_name_snapshot VARCHAR(100) NOT NULL,
    shift_color_snapshot VARCHAR(7) NOT NULL,
    check_in_early_minutes_snapshot INTEGER NOT NULL,
    late_tolerance_minutes_snapshot INTEGER NOT NULL,
    work_date DATE NOT NULL,
    scheduled_start_utc TIMESTAMPTZ NOT NULL,
    scheduled_end_utc TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    cancelled_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    cancelled_at_utc TIMESTAMPTZ,
    note VARCHAR(1000),
    cancellation_reason VARCHAR(500),
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_work_schedule_window
        CHECK (scheduled_end_utc > scheduled_start_utc),
    CONSTRAINT chk_work_schedule_snapshot_minutes
        CHECK (check_in_early_minutes_snapshot BETWEEN 0 AND 240
            AND late_tolerance_minutes_snapshot BETWEEN 0 AND 240),
    CONSTRAINT chk_work_schedule_status
        CHECK (status IN ('SCHEDULED', 'FULFILLED', 'CANCELLED', 'ABSENT')),
    CONSTRAINT chk_work_schedule_cancelled_fields
        CHECK ((status = 'CANCELLED') = (cancelled_at_utc IS NOT NULL))
);

ALTER TABLE work_schedule_assignments
    ADD CONSTRAINT ex_work_schedule_no_overlap
    EXCLUDE USING gist (
        employee_id WITH =,
        tstzrange(scheduled_start_utc, scheduled_end_utc, '[)') WITH &&
    ) WHERE (status <> 'CANCELLED');

CREATE INDEX idx_work_schedule_employee_window
    ON work_schedule_assignments(employee_id, scheduled_start_utc, scheduled_end_utc);

CREATE INDEX idx_work_schedule_status_start
    ON work_schedule_assignments(status, scheduled_start_utc);

CREATE INDEX idx_work_shift_template_active_order
    ON work_shift_templates(active, sort_order, start_time);

CREATE TABLE work_shift_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    assignment_id BIGINT NOT NULL REFERENCES work_schedule_assignments(id) ON DELETE RESTRICT,
    employee_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    status VARCHAR(20) NOT NULL,
    actual_check_in_utc TIMESTAMPTZ NOT NULL,
    actual_check_out_utc TIMESTAMPTZ,
    check_in_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    check_out_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    note VARCHAR(1000),
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_work_shift_session_assignment UNIQUE (assignment_id),
    CONSTRAINT chk_work_shift_session_status
        CHECK (status IN ('ACTIVE', 'CLOSED', 'AUTO_CLOSED')),
    CONSTRAINT chk_work_shift_session_checkout
        CHECK ((status = 'ACTIVE' AND actual_check_out_utc IS NULL)
            OR (status <> 'ACTIVE' AND actual_check_out_utc IS NOT NULL))
);

CREATE UNIQUE INDEX uk_work_shift_session_active_employee
    ON work_shift_sessions(employee_id)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_work_shift_session_employee_checkin
    ON work_shift_sessions(employee_id, actual_check_in_utc DESC);

CREATE INDEX idx_work_shift_session_status
    ON work_shift_sessions(status, actual_check_in_utc);

ALTER TABLE cashier_shifts
    ADD COLUMN work_shift_session_id BIGINT;

ALTER TABLE cashier_shifts
    ADD CONSTRAINT fk_cashier_shift_work_session
    FOREIGN KEY (work_shift_session_id)
    REFERENCES work_shift_sessions(id) ON DELETE RESTRICT;

CREATE UNIQUE INDEX uk_cashier_shift_work_session
    ON cashier_shifts(work_shift_session_id)
    WHERE work_shift_session_id IS NOT NULL;

INSERT INTO work_shift_templates (
    code, name, start_time, end_time, check_in_early_minutes,
    late_tolerance_minutes, color, sort_order, active
) VALUES
    ('SANG', 'Ca sáng', TIME '06:00', TIME '14:00', 30, 15, '#B8944F', 10, TRUE),
    ('CHIEU', 'Ca chiều', TIME '14:00', TIME '22:00', 30, 15, '#315B7D', 20, TRUE),
    ('TOI', 'Ca tối', TIME '22:00', TIME '06:00', 30, 15, '#0F2A43', 30, TRUE)
ON CONFLICT (code) DO NOTHING;
