-- Monthly workforce planning and staff self-registration.
-- Attendance and cashier lifecycle remain owned by V30 work schedule/session tables.

CREATE TABLE work_shift_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    shift_template_id BIGINT NOT NULL
        REFERENCES work_shift_templates(id) ON DELETE RESTRICT,
    work_date DATE NOT NULL,
    required_staff INTEGER NOT NULL DEFAULT 1,
    note VARCHAR(500),
    updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_work_shift_requirement
        UNIQUE (shift_template_id, work_date),
    CONSTRAINT chk_work_shift_required_staff
        CHECK (required_staff BETWEEN 0 AND 100)
);

CREATE INDEX idx_work_shift_requirement_date
    ON work_shift_requirements(work_date, shift_template_id);

CREATE TABLE work_shift_registration_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    employee_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    shift_template_id BIGINT NOT NULL
        REFERENCES work_shift_templates(id) ON DELETE RESTRICT,
    work_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    staff_note VARCHAR(500),
    admin_reason VARCHAR(500),
    reviewed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at_utc TIMESTAMPTZ,
    assignment_id BIGINT REFERENCES work_schedule_assignments(id) ON DELETE RESTRICT,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_work_shift_registration_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT chk_work_shift_registration_review
        CHECK (
            (status = 'PENDING'
                AND reviewed_by IS NULL
                AND reviewed_at_utc IS NULL
                AND assignment_id IS NULL)
            OR (status = 'CANCELLED'
                AND reviewed_by IS NULL
                AND reviewed_at_utc IS NULL
                AND assignment_id IS NULL)
            OR (status = 'REJECTED'
                AND reviewed_by IS NOT NULL
                AND reviewed_at_utc IS NOT NULL
                AND assignment_id IS NULL)
            OR (status = 'APPROVED'
                AND reviewed_by IS NOT NULL
                AND reviewed_at_utc IS NOT NULL
                AND assignment_id IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uk_work_shift_registration_pending
    ON work_shift_registration_requests(employee_id, shift_template_id, work_date)
    WHERE status = 'PENDING';

CREATE INDEX idx_work_shift_registration_month
    ON work_shift_registration_requests(work_date, shift_template_id, status);

CREATE INDEX idx_work_shift_registration_employee
    ON work_shift_registration_requests(employee_id, work_date, status);
