-- Audit trail, exceptional checkout reconciliation and durable alert delivery.
--
-- This migration is intentionally additive. Legacy audit text columns remain
-- readable and no reservation/payment/refund state is rewritten.

ALTER TABLE reservation_audit_logs
    ADD COLUMN old_value_json JSONB,
    ADD COLUMN new_value_json JSONB,
    ADD COLUMN detail_json JSONB,
    ADD COLUMN risk_level varchar(16) NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN category varchar(32) NOT NULL DEFAULT 'BUSINESS',
    ADD COLUMN dedup_key varchar(191);

ALTER TABLE reservation_audit_logs
    ADD CONSTRAINT chk_audit_old_value_object
        CHECK (old_value_json IS NULL OR jsonb_typeof(old_value_json) = 'object') NOT VALID,
    ADD CONSTRAINT chk_audit_new_value_object
        CHECK (new_value_json IS NULL OR jsonb_typeof(new_value_json) = 'object') NOT VALID,
    ADD CONSTRAINT chk_audit_detail_object
        CHECK (detail_json IS NULL OR jsonb_typeof(detail_json) = 'object') NOT VALID,
    ADD CONSTRAINT chk_audit_risk_level
        CHECK (risk_level IN ('NORMAL', 'MEDIUM', 'HIGH', 'CRITICAL')) NOT VALID;

CREATE INDEX idx_audit_target_occurred
    ON reservation_audit_logs (target_type, target_id, occurred_at_utc DESC, id DESC);

CREATE INDEX idx_audit_actor_occurred
    ON reservation_audit_logs (actor_user_id, occurred_at_utc DESC, id DESC);

CREATE INDEX idx_audit_action_occurred
    ON reservation_audit_logs (action_code, occurred_at_utc DESC, id DESC);

CREATE INDEX idx_audit_correlation_id
    ON reservation_audit_logs (correlation_id)
    WHERE correlation_id IS NOT NULL;

CREATE INDEX idx_audit_risk_occurred
    ON reservation_audit_logs (risk_level, occurred_at_utc DESC, id DESC)
    WHERE risk_level IN ('HIGH', 'CRITICAL');

CREATE UNIQUE INDEX uk_audit_dedup_key
    ON reservation_audit_logs (dedup_key)
    WHERE dedup_key IS NOT NULL;

ALTER TABLE payment_refunds
    ADD COLUMN refund_detail_json JSONB;

ALTER TABLE payment_refunds
    ADD CONSTRAINT chk_payment_refunds_detail_object
        CHECK (refund_detail_json IS NULL OR jsonb_typeof(refund_detail_json) = 'object') NOT VALID;

CREATE TABLE checkout_reconciliation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reservation_id bigint NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    status varchar(32) NOT NULL,
    mismatch_snapshot_json JSONB NOT NULL,
    reason_code varchar(80) NOT NULL,
    reason_note text NOT NULL,
    requested_by bigint,
    requested_by_name varchar(150) NOT NULL,
    requested_by_role varchar(32) NOT NULL,
    correction_type varchar(32),
    correction_detail_json JSONB,
    resolution_reason_code varchar(80),
    resolution_note text,
    resolved_by bigint,
    resolved_by_name varchar(150),
    resolved_by_role varchar(32),
    evidence_asset_id bigint,
    idempotency_key varchar(128) NOT NULL,
    actor_scope varchar(190) NOT NULL,
    correlation_id varchar(128) NOT NULL,
    created_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at_utc TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT fk_checkout_reconciliation_reservation
        FOREIGN KEY (reservation_id) REFERENCES reservations (id),
    CONSTRAINT fk_checkout_reconciliation_requester
        FOREIGN KEY (requested_by) REFERENCES users (id),
    CONSTRAINT fk_checkout_reconciliation_resolver
        FOREIGN KEY (resolved_by) REFERENCES users (id),
    CONSTRAINT fk_checkout_reconciliation_evidence
        FOREIGN KEY (evidence_asset_id) REFERENCES media_assets (id),
    CONSTRAINT uk_checkout_reconciliation_idempotency
        UNIQUE (idempotency_key, actor_scope),
    CONSTRAINT chk_checkout_reconciliation_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT chk_checkout_reconciliation_snapshot
        CHECK (jsonb_typeof(mismatch_snapshot_json) = 'object'),
    CONSTRAINT chk_checkout_reconciliation_correction
        CHECK (correction_detail_json IS NULL OR jsonb_typeof(correction_detail_json) = 'object'),
    CONSTRAINT chk_checkout_reconciliation_resolution
        CHECK (status = 'PENDING' OR resolved_at_utc IS NOT NULL)
);

CREATE INDEX idx_checkout_reconciliation_reservation_created
    ON checkout_reconciliation_requests (reservation_id, created_at_utc DESC, id DESC);

CREATE INDEX idx_checkout_reconciliation_pending
    ON checkout_reconciliation_requests (created_at_utc, id)
    WHERE status = 'PENDING';

CREATE TABLE audit_notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    audit_log_id bigint NOT NULL,
    notification_type varchar(32) NOT NULL,
    recipient_email varchar(255) NOT NULL,
    status varchar(24) NOT NULL DEFAULT 'PENDING',
    payload_json JSONB NOT NULL,
    attempts int NOT NULL DEFAULT 0,
    next_attempt_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_attempt_at_utc TIMESTAMP(6) WITH TIME ZONE,
    sent_at_utc TIMESTAMP(6) WITH TIME ZONE,
    last_error varchar(500),
    created_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT fk_audit_notification_audit_log
        FOREIGN KEY (audit_log_id) REFERENCES reservation_audit_logs (id),
    CONSTRAINT uk_audit_notification_delivery
        UNIQUE (audit_log_id, notification_type, recipient_email),
    CONSTRAINT chk_audit_notification_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'FAILED')),
    CONSTRAINT chk_audit_notification_payload
        CHECK (jsonb_typeof(payload_json) = 'object'),
    CONSTRAINT chk_audit_notification_attempts
        CHECK (attempts >= 0)
);

CREATE INDEX idx_audit_notification_due
    ON audit_notification_outbox (next_attempt_at_utc, id)
    WHERE status IN ('PENDING', 'FAILED');
