CREATE TABLE oauth_login_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    consumed_at_utc TIMESTAMP(6) WITH TIME ZONE,
    created_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_oauth_login_tickets_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_oauth_login_tickets_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_oauth_login_tickets_user_id
    ON oauth_login_tickets (user_id);

CREATE INDEX idx_oauth_login_tickets_expiry
    ON oauth_login_tickets (expires_at_utc);
