CREATE TABLE oauth_profile_completion_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    image_url VARCHAR(500),
    expires_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    consumed_at_utc TIMESTAMP(6) WITH TIME ZONE,
    created_at_utc TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_oauth_profile_completion_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_oauth_profile_completion_expiry
    ON oauth_profile_completion_tickets (expires_at_utc);

CREATE INDEX idx_oauth_profile_completion_identity
    ON oauth_profile_completion_tickets (provider, provider_subject);
