import type { Metadata } from "next";
import InformationPage, { type InformationSection } from "@/components/guest/InformationPage";

export const metadata: Metadata = { title: "Chính sách hủy lịch" };

const sections: InformationSection[] = [
  { title: { vi: "Gửi yêu cầu hủy", en: "Submit a cancellation request" }, body: { vi: "Khách đăng nhập mở Đơn của tôi để gửi yêu cầu hủy khi trạng thái đơn cho phép. Khách vãng lai dùng mã đơn và token tra cứu. Gửi yêu cầu không đồng nghĩa khoản hoàn đã hoàn tất.", en: "Signed-in guests submit cancellation requests from My bookings when the current status allows it. Guest bookings use the booking code and lookup token. A request does not mean a refund is complete." } },
  { title: { vi: "Điều kiện và số tiền hoàn", en: "Refund eligibility and amount" }, body: { vi: "Số tiền hoàn được tính từ khoản đã thực nhận, nghĩa vụ thanh toán, trạng thái lưu trú và quy định hủy được khách sạn phê duyệt. Hệ thống không cho hoàn vượt số tiền còn phải hoàn và ngăn tạo hoàn trùng.", en: "The refundable amount depends on received funds, payment obligations, stay status, and the hotel-approved cancellation rules. The system prevents refunds above the remaining obligation and duplicate refunds." } },
  { title: { vi: "Hoàn qua QR", en: "QR refunds" }, body: { vi: "Khách sạn chuyển đúng mã hoàn và số tiền; hệ thống tự đối chiếu xác nhận tiền ra từ ngân hàng. Nếu ngân hàng không gửi xác nhận sau thời gian chờ, nhân viên mới dùng fallback có ghi lý do; ảnh biên lai chỉ là tùy chọn. Không cung cấp OTP hoặc mật khẩu ngân hàng.", en: "The hotel transfers the exact refund code and amount, and the system automatically reconciles the outgoing bank transaction. If confirmation is unavailable after the waiting period, staff may use a reasoned fallback; a receipt image is optional. Never provide an OTP or bank password." } },
  { title: { vi: "Hoàn tiền mặt", en: "Cash refunds" }, body: { vi: "Hoàn tiền mặt không bắt buộc tải minh chứng ngân hàng nhưng vẫn phải được nhân viên ghi nhận trong ledger và audit. Việc nhận tiền cần được xác nhận tại quầy.", en: "Cash refunds do not require bank proof, but staff must still record them in the ledger and audit trail. Receipt of cash should be confirmed at the front desk." } },
  { title: { vi: "Trạng thái đang xử lý", en: "Pending refund status" }, body: { vi: "Refund CANCELLED không xóa nghĩa vụ hoàn còn lại. Đơn chỉ được checkout khi các nghĩa vụ thanh toán và hoàn tiền liên quan đã hoàn tất hoặc được xử lý theo quyền force checkout của vận hành.", en: "A CANCELLED refund does not remove the remaining refund obligation. Checkout occurs only when related payment and refund obligations are complete or operations use an authorized force-checkout flow." } },
];

export default function CancellationPolicyPage() {
  return <InformationPage eyebrow={{ vi: "Hủy và hoàn tiền", en: "Cancellation and refunds" }} title={{ vi: "Chính sách hủy lịch", en: "Cancellation policy" }} intro={{ vi: "Cách gửi yêu cầu hủy, cung cấp tài khoản nhận tiền và theo dõi đối soát hoàn tiền.", en: "How to request cancellation, provide payout details, and track refund reconciliation." }} sections={sections} notice={{ vi: "Mức phí và thời hạn hoàn chính thức cần khách sạn phê duyệt trước khi production; website không tự hứa một số ngày xử lý cố định.", en: "Official fees and refund timelines require hotel approval before production; the website does not promise a fixed processing period." }} primaryAction={{ href: "/my-bookings", label: { vi: "Mở Đơn của tôi", en: "Open My bookings" } }} secondaryAction={{ href: "/support", label: { vi: "Cần hỗ trợ", en: "Get support" } }} />;
}
