package com.hotel.backend.constant;

public enum ReservationAuditAction {
    CONFIRM,
    CHECK_IN,
    UPDATE_CHECKOUT_FEE,
    REFUND,
    CHECK_OUT,
    PRINT_INVOICE,
    CANCEL,
    MARK_NO_SHOW,
    SESSION_EXPIRED,
    PAYMENT_ABANDONED,
    PAYMENT_RECEIVED,
    PAYMENT_SESSION_CREATED,
    RECOVERED_ON_TIME_PAYMENT,
    PROVIDER_EVENT_MATCHED,
    PROVIDER_EVENT_IGNORED,
    PROVIDER_EVENT_REFUND_CREATED,
    ROOM_HOLD_RELEASED_MANUALLY,
    ROOM_HOLD_AUTO_EXPIRED,
    RESERVATION_AUTO_CANCELLED,
    PAYMENT_MARKED_PAID_MANUALLY,
    PRICE_OVERRIDDEN,
    CHECKOUT_RECONCILIATION_REQUESTED,
    CHECKOUT_RECONCILIATION_REJECTED,
    CHECKOUT_RECONCILIATION_PASSED,
    CHECKOUT_RECONCILIATION_OVERRIDDEN,
    USER_ROLE_CHANGED,
    ROOM_CREATED,
    ROOM_UPDATED,
    ROOM_DELETED,
    ROOM_TYPE_CREATED,
    ROOM_TYPE_UPDATED,
    ROOM_TYPE_DELETED,
    FACILITY_CREATED,
    FACILITY_UPDATED,
    FACILITY_DELETED,
    GALLERY_CREATED,
    GALLERY_UPDATED,
    GALLERY_DELETED,
    LOGIN_SUCCESS,
    LOGOUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_RESET_BY_ADMIN,
    PROVIDER_EVENT_REVIEW_REQUIRED,
    WEBHOOK_AUTHENTICATION_REJECTED;

    public AuditRiskLevel riskLevel() {
        return switch (this) {
            case USER_ROLE_CHANGED, CHECKOUT_RECONCILIATION_OVERRIDDEN,
                    PAYMENT_MARKED_PAID_MANUALLY, PRICE_OVERRIDDEN,
                    ROOM_HOLD_RELEASED_MANUALLY, PASSWORD_RESET_BY_ADMIN,
                    PROVIDER_EVENT_REVIEW_REQUIRED,
                    WEBHOOK_AUTHENTICATION_REJECTED -> AuditRiskLevel.HIGH;
            case PROVIDER_EVENT_IGNORED, PROVIDER_EVENT_REFUND_CREATED,
                    CHECKOUT_RECONCILIATION_REQUESTED,
                    CHECKOUT_RECONCILIATION_REJECTED,
                    ROOM_DELETED, ROOM_TYPE_DELETED,
                    FACILITY_DELETED, GALLERY_DELETED,
                    PASSWORD_CHANGED, PASSWORD_RESET_COMPLETED -> AuditRiskLevel.MEDIUM;
            default -> AuditRiskLevel.NORMAL;
        };
    }

    public AuditCategory category() {
        return switch (this) {
            case PAYMENT_ABANDONED, PAYMENT_RECEIVED, PAYMENT_SESSION_CREATED,
                    RECOVERED_ON_TIME_PAYMENT, PROVIDER_EVENT_MATCHED,
                    PROVIDER_EVENT_IGNORED, PROVIDER_EVENT_REFUND_CREATED,
                    PROVIDER_EVENT_REVIEW_REQUIRED,
                    WEBHOOK_AUTHENTICATION_REJECTED,
                    PAYMENT_MARKED_PAID_MANUALLY -> AuditCategory.PAYMENT;
            case REFUND -> AuditCategory.REFUND;
            case ROOM_HOLD_RELEASED_MANUALLY, ROOM_HOLD_AUTO_EXPIRED -> AuditCategory.ROOM_HOLD;
            case UPDATE_CHECKOUT_FEE, CHECK_OUT, CHECKOUT_RECONCILIATION_REQUESTED,
                    CHECKOUT_RECONCILIATION_REJECTED,
                    CHECKOUT_RECONCILIATION_PASSED,
                    CHECKOUT_RECONCILIATION_OVERRIDDEN -> AuditCategory.CHECKOUT;
            case USER_ROLE_CHANGED, LOGIN_SUCCESS, LOGOUT, PASSWORD_CHANGED,
                    PASSWORD_RESET_COMPLETED, PASSWORD_RESET_BY_ADMIN -> AuditCategory.SECURITY;
            case ROOM_CREATED, ROOM_UPDATED, ROOM_DELETED,
                    ROOM_TYPE_CREATED, ROOM_TYPE_UPDATED, ROOM_TYPE_DELETED,
                    FACILITY_CREATED, FACILITY_UPDATED, FACILITY_DELETED,
                    GALLERY_CREATED, GALLERY_UPDATED, GALLERY_DELETED -> AuditCategory.BUSINESS;
            case SESSION_EXPIRED, RESERVATION_AUTO_CANCELLED -> AuditCategory.SYSTEM;
            default -> AuditCategory.RESERVATION;
        };
    }

    public boolean requiresAlert() {
        return riskLevel() == AuditRiskLevel.HIGH || riskLevel() == AuditRiskLevel.CRITICAL;
    }
}
