package com.hotel.backend.constant;

public enum ReservationAuditAction {
    CONFIRM,
    CHECK_IN,
    RESERVATION_EXTENDED,
    UPDATE_CHECKOUT_FEE,
    REFUND,
    CHECK_OUT,
    PRINT_INVOICE,
    CANCEL,
    MARK_NO_SHOW,
    SESSION_EXPIRED,
    PAYMENT_ABANDONED,
    PAYMENT_RECEIVED,
    PAYMENT_SESSION_CREATED,
    RECOVERED_ON_TIME_PAYMENT,
    PROVIDER_EVENT_MATCHED,
    PROVIDER_EVENT_IGNORED,
    PROVIDER_EVENT_REFUND_CREATED,
    ROOM_HOLD_RELEASED_MANUALLY,
    ROOM_HOLD_AUTO_EXPIRED,
    RESERVATION_AUTO_CANCELLED,
    PAYMENT_MARKED_PAID_MANUALLY,
    PRICE_OVERRIDDEN,
    CHECKOUT_RECONCILIATION_REQUESTED,
    CHECKOUT_RECONCILIATION_REJECTED,
    CHECKOUT_RECONCILIATION_RESOLVED_AUTOMATICALLY,
    CHECKOUT_RECONCILIATION_PASSED,
    CHECKOUT_RECONCILIATION_OVERRIDDEN,
    USER_CREATED,
    USER_DEACTIVATED,
    USER_ROLE_CHANGED,
    USERNAME_CONFLICT_REMEDIATED,
    ROOM_CREATED,
    ROOM_UPDATED,
    ROOM_DELETED,
    ROOM_TYPE_CREATED,
    ROOM_TYPE_UPDATED,
    ROOM_TYPE_DELETED,
    FACILITY_CREATED,
    FACILITY_UPDATED,
    FACILITY_DELETED,
    GALLERY_CREATED,
    GALLERY_UPDATED,
    GALLERY_DELETED,
    SERVICE_CATALOG_CREATED,
    SERVICE_CATALOG_UPDATED,
    SERVICE_CATALOG_DEACTIVATED,
    SERVICE_CATALOG_REACTIVATED,
    RESERVATION_SERVICE_ADDED,
    RESERVATION_SERVICE_CONFIRMED,
    RESERVATION_SERVICE_REPRICED,
    RESERVATION_SERVICE_FULFILLED,
    RESERVATION_SERVICE_CANCELLED,
    CASHIER_SHIFT_OPENED,
    CASHIER_SHIFT_CLOSED,
    CASH_MOVEMENT_RECORDED,
    CASH_VARIANCE_RECORDED,
    BUSINESS_DAY_CLOSED,
    FINANCIAL_LATE_POSTING,
    LOGIN_SUCCESS,
    LOGOUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_RESET_BY_ADMIN,
    PROVIDER_EVENT_REVIEW_REQUIRED,
    WEBHOOK_AUTHENTICATION_REJECTED;

    public AuditRiskLevel riskLevel() {
        return switch (this) {
            case USER_ROLE_CHANGED, USER_DEACTIVATED, CHECKOUT_RECONCILIATION_OVERRIDDEN,
                    PAYMENT_MARKED_PAID_MANUALLY, PRICE_OVERRIDDEN,
                    ROOM_HOLD_RELEASED_MANUALLY, PASSWORD_RESET_BY_ADMIN,
                    CASH_VARIANCE_RECORDED,
                    BUSINESS_DAY_CLOSED, FINANCIAL_LATE_POSTING,
                    PROVIDER_EVENT_REVIEW_REQUIRED,
                    WEBHOOK_AUTHENTICATION_REJECTED -> AuditRiskLevel.HIGH;
            case PROVIDER_EVENT_IGNORED, PROVIDER_EVENT_REFUND_CREATED,
                    CHECKOUT_RECONCILIATION_REQUESTED,
                    CHECKOUT_RECONCILIATION_REJECTED,
                    CHECKOUT_RECONCILIATION_RESOLVED_AUTOMATICALLY,
                    ROOM_DELETED, ROOM_TYPE_DELETED,
                    FACILITY_DELETED, GALLERY_DELETED, USER_CREATED,
                    USERNAME_CONFLICT_REMEDIATED,
                    PASSWORD_CHANGED, PASSWORD_RESET_COMPLETED -> AuditRiskLevel.MEDIUM;
            default -> AuditRiskLevel.NORMAL;
        };
    }

    public AuditCategory category() {
        return switch (this) {
            case PAYMENT_ABANDONED, PAYMENT_RECEIVED, PAYMENT_SESSION_CREATED,
                    RECOVERED_ON_TIME_PAYMENT, PROVIDER_EVENT_MATCHED,
                    PROVIDER_EVENT_IGNORED, PROVIDER_EVENT_REFUND_CREATED,
                    PROVIDER_EVENT_REVIEW_REQUIRED,
                    WEBHOOK_AUTHENTICATION_REJECTED,
                    PAYMENT_MARKED_PAID_MANUALLY,
                    CASHIER_SHIFT_OPENED, CASHIER_SHIFT_CLOSED,
                    CASH_MOVEMENT_RECORDED, CASH_VARIANCE_RECORDED,
                    BUSINESS_DAY_CLOSED, FINANCIAL_LATE_POSTING -> AuditCategory.PAYMENT;
            case REFUND -> AuditCategory.REFUND;
            case ROOM_HOLD_RELEASED_MANUALLY, ROOM_HOLD_AUTO_EXPIRED -> AuditCategory.ROOM_HOLD;
            case UPDATE_CHECKOUT_FEE, CHECK_OUT, CHECKOUT_RECONCILIATION_REQUESTED,
                    CHECKOUT_RECONCILIATION_REJECTED,
                    CHECKOUT_RECONCILIATION_RESOLVED_AUTOMATICALLY,
                    CHECKOUT_RECONCILIATION_PASSED,
                    CHECKOUT_RECONCILIATION_OVERRIDDEN -> AuditCategory.CHECKOUT;
            case USER_CREATED, USER_DEACTIVATED, USER_ROLE_CHANGED, USERNAME_CONFLICT_REMEDIATED,
                    LOGIN_SUCCESS, LOGOUT, PASSWORD_CHANGED,
                    PASSWORD_RESET_COMPLETED, PASSWORD_RESET_BY_ADMIN -> AuditCategory.SECURITY;
            case ROOM_CREATED, ROOM_UPDATED, ROOM_DELETED,
                    ROOM_TYPE_CREATED, ROOM_TYPE_UPDATED, ROOM_TYPE_DELETED,
                    FACILITY_CREATED, FACILITY_UPDATED, FACILITY_DELETED,
                    GALLERY_CREATED, GALLERY_UPDATED, GALLERY_DELETED,
                    SERVICE_CATALOG_CREATED, SERVICE_CATALOG_UPDATED,
                    SERVICE_CATALOG_DEACTIVATED, SERVICE_CATALOG_REACTIVATED -> AuditCategory.BUSINESS;
            case SESSION_EXPIRED, RESERVATION_AUTO_CANCELLED -> AuditCategory.SYSTEM;
            default -> AuditCategory.RESERVATION;
        };
    }

    public AuditScope scope() {
        return switch (category()) {
            case BUSINESS, SECURITY -> AuditScope.MANAGEMENT;
            default -> AuditScope.OPERATION;
        };
    }

    public boolean requiresAlert() {
        return riskLevel() == AuditRiskLevel.HIGH || riskLevel() == AuditRiskLevel.CRITICAL;
    }
}
